import { describe, expect, it } from "vitest";
import { buildEffectiveCombatStats, evaluatePredicate, evaluateValueExpression, type CombatContext } from "./combat-context";
import type { FinalStats } from "./models";

const stats: FinalStats = { hp:10000,attack:1000,defense:500,critRate:5,critDamage:150,energyRegen:130,healingBonus:0,tuneBreakBoost:0,elementalDamageBonus:{aero:0,glacio:0,electro:0,fusion:0,havoc:0,spectro:0},damageTypeBonus:{basicAttack:0,heavyAttack:0,resonanceSkill:0,resonanceLiberation:0,introSkill:0,echoSkill:0} };
const context:CombatContext={timestamp:0,actorId:"actor",ownerId:"actor",targetId:"enemy",panelStats:stats,actorHpRatio:.4,targetHpRatio:.8,resources:{gauge:{current:10,max:10}},states:["form"],targetStatuses:{mark:2}};
describe("Combat Context V0.2",()=>{
  it("applique les pourcentages à la base vérifiée et les flats sans muter le panneau",()=>{const before=structuredClone(stats);const result=buildEffectiveCombatStats(stats,{attack:500,hp:8000,defense:400},[{stat:"attack",mode:"percent",value:20},{stat:"attack",mode:"flat",value:50},{stat:"hp",mode:"percent",value:10},{stat:"defense",mode:"percent",value:25}]);expect(result.stats).toMatchObject({attack:1150,hp:10800,defense:600});expect(stats).toEqual(before);expect(result.audit[0]).toMatchObject({panel:1000,basis:500,percentContribution:100,flatContribution:50,effective:1150});});
  it("refuse un pourcentage sans base stat",()=>expect(buildEffectiveCombatStats(stats,{},[{stat:"attack",mode:"percent",value:10}]).diagnostics).toEqual(["missing-base-stat-basis:attack"]));
  it("évalue stat, cap, stacks, seuil et rank sans interpolation",()=>{expect(evaluateValueExpression({kind:"cap",max:50,value:{kind:"multiply",values:[{kind:"constant",value:2},{kind:"max",values:[{kind:"constant",value:0},{kind:"subtract",left:{kind:"stat",stat:"energyRegen"},right:{kind:"constant",value:125}}]}]}},context).value).toBe(10);expect(evaluateValueExpression({kind:"stack-threshold",threshold:6,then:{kind:"constant",value:20}},context,{stacks:6}).value).toBe(20);expect(evaluateValueExpression({kind:"rank",values:{1:12}},context,{rank:2}).diagnostics[0].code).toBe("missing-rank-value");});
  it("compose AND OR NOT et les conditions HP, ressource, status",()=>{const predicate={kind:"and",predicates:[{kind:"number",field:"actorHpRatio",comparison:"lte",value:.5},{kind:"or",predicates:[{kind:"resource",resourceId:"gauge",comparison:"max"},{kind:"target-has-status",id:"missing"}]},{kind:"not",predicate:{kind:"number",field:"targetHpRatio",comparison:"lte",value:.5}}]} as const;expect(evaluatePredicate(predicate,context).status).toBe("matched");expect(evaluatePredicate({kind:"target-has-status",id:"mark",minStacks:2},context).status).toBe("matched");});
  it("traite une dimension identitaire absente comme non applicable",()=>{expect(evaluatePredicate({kind:"identity",field:"actionId",anyOf:["some-action"]},context)).toEqual({status:"ignored",reason:"dimension-absent"});expect(evaluatePredicate({kind:"action-category",anyOf:["coordinated"]},context)).toEqual({status:"ignored",reason:"dimension-absent"});});
  it("conserve unsupported pour une vraie donnée numérique manquante",()=>expect(evaluatePredicate({kind:"number",field:"targetHpRatio",comparison:"lte",value:.5},{...context,targetHpRatio:undefined}).status).toBe("unsupported"));
  it("rejette les valeurs non finies",()=>expect(evaluateValueExpression({kind:"constant",value:Infinity},context).status).toBe("unsupported"));
});
