import type { SnapshotPolicy, StatusDefinition } from "./effect-models";
import type { CombatEvent } from "./state-engine";

const priority:Readonly<Record<string,number>>={"effect-expired":0,"state-exit":1,"resource-consumed":2,"rotation-step-start":3,"action-start":4,"action-hit":5,"damage-dealt":6,"action-end":7,"effect-activated":8};
export function compareCombatEvents(a:CombatEvent,b:CombatEvent):number{return a.timestamp-b.timestamp||(priority[a.kind]??50)-(priority[b.kind]??50)||a.id.localeCompare(b.id);}
export interface EventQueueLimits {maxProcessedEvents:number;maxChainDepth:number;}
export interface QueueDiagnostic {code:"event-limit-reached"|"chain-depth-reached"|"zero-time-cycle"|"invalid-event";message:string;eventId?:string;}
export interface QueueResult {processed:readonly CombatEvent[];diagnostics:readonly QueueDiagnostic[];partial:boolean;}
export class CombatEventQueue {private queue:CombatEvent[]=[];private seen=new Set<string>();readonly diagnostics:QueueDiagnostic[]=[];constructor(private readonly limits:EventQueueLimits={maxProcessedEvents:10000,maxChainDepth:32}){}enqueue(event:CombatEvent):boolean{if(!Number.isFinite(event.timestamp)||event.timestamp<0){this.diagnostics.push({code:"invalid-event",message:"Timestamp must be finite and non-negative.",eventId:event.id});return false;}if((event.depth??0)>this.limits.maxChainDepth){this.diagnostics.push({code:"chain-depth-reached",message:"Maximum derived-event chain depth reached.",eventId:event.id});return false;}const signature=`${event.originEventId??event.id}|${event.timestamp}|${event.kind}|${event.actionId??""}|${event.depth??0}`;if(this.seen.has(signature)){this.diagnostics.push({code:"zero-time-cycle",message:"Repeated derived event was rejected.",eventId:event.id});return false;}this.seen.add(signature);this.queue.push({...event});this.queue.sort(compareCombatEvents);return true;}drain(handler:(event:CombatEvent)=>readonly CombatEvent[]):QueueResult{const processed:CombatEvent[]=[];while(this.queue.length&&processed.length<this.limits.maxProcessedEvents){const event=this.queue.shift()!;processed.push(event);for(const next of handler(event))this.enqueue(next);}if(this.queue.length)this.diagnostics.push({code:"event-limit-reached",message:`Stopped after ${this.limits.maxProcessedEvents} events.`});return{processed,diagnostics:this.diagnostics,partial:this.diagnostics.length>0};}}

export function schedulePeriodicStatus(status:StatusDefinition,applied:CombatEvent):{events:CombatEvent[];diagnostics:QueueDiagnostic[]}{const events:CombatEvent[]=[],diagnostics:QueueDiagnostic[]=[];if(!status.periodic)return{events,diagnostics};const {intervalSeconds,maxTicks,emittedAction}=status.periodic;if(!Number.isFinite(intervalSeconds)||intervalSeconds<=0||!Number.isInteger(maxTicks)||maxTicks<0){diagnostics.push({code:"invalid-event",message:"Periodic cadence is invalid.",eventId:applied.id});return{events,diagnostics};}for(let i=1;i<=maxTicks;i++)events.push({...applied,id:`${applied.id}:tick:${i}`,timestamp:applied.timestamp+intervalSeconds*i,kind:"action-hit",actionId:emittedAction.actionId,actorId:emittedAction.actorId??applied.ownerId,external:false,originEventId:applied.id,depth:(applied.depth??0)+1,payload:{...emittedAction,statusId:status.id,tick:i,snapshot:emittedAction.snapshot}});return{events,diagnostics};}
export function validateSnapshot(policy:SnapshotPolicy):QueueDiagnostic|undefined{return policy.stats==="unknown"||policy.stacks==="unknown"?{code:"invalid-event",message:"snapshot-policy-required"}:undefined;}
