import {describe,expect,it} from "vitest";
import type {EffectDefinition, TriggerOperation} from "./effect-models";
import {advanceState,emptyCombatState,processEvent,type CombatEvent,type CombatState} from "./state-engine";
import type {CombatAction,FinalStats,Resonator,UserBuild} from "./models";
import type {TemporalTimeline} from "./temporal-engine";
import {simulatePersonalCombat} from "./personal-combat-simulation";

const source={kind:"technical-fixture" as const,source:"consolidation"};
const stats:FinalStats={hp:10000,attack:1000,defense:500,critRate:0,critDamage:150,energyRegen:100,healingBonus:0,tuneBreakBoost:0,elementalDamageBonus:{aero:0,glacio:0,electro:0,fusion:0,havoc:0,spectro:0},damageTypeBonus:{basicAttack:0,heavyAttack:0,resonanceSkill:0,resonanceLiberation:50,introSkill:0,echoSkill:0}};
const action=(id:string,percent=100,damageType:CombatAction["damageType"]="basicAttack"):CombatAction=>({id,name:id,talent:"basicAttack",damageType,level:10,multipliers:[{percent,hits:1}],castDurationSeconds:{value:1,confidence:"technical-fixture"},recoverySeconds:{value:null,confidence:"unknown"},hitTimingsSeconds:{value:null,confidence:"unknown"},source});
const build:UserBuild={id:"b",resonatorId:"r",sourcePresetId:"p",characterLevel:90,sequence:0,skillLevels:{basicAttack:10,resonanceSkill:10,forteCircuit:10,resonanceLiberation:10,introSkill:10},weapon:{weaponId:"w",level:90,rank:1},finalStats:stats,createdAt:"",updatedAt:""};
const timeline=(hits:readonly number[]|null=null):TemporalTimeline=>({rotationId:"r",name:"r",policy:"no-quickswap",targetDurationSeconds:null,targetConfidence:null,targetSource:null,rawDurationSeconds:3,measuredDurationSeconds:3,estimatedDurationSeconds:0,calibrationFactor:null,finalDurationSeconds:3,confidence:"measured",diagnostics:[],entries:[{index:0,stepId:"s",label:"base",actionId:"base",startTimeSeconds:0,endTimeSeconds:3,baseDurationSeconds:3,effectiveDurationSeconds:3,confidence:"measured",source:"fixture",recoverySeconds:null,cancelTimingSeconds:null,hitTimingsSeconds:hits,notes:[]}]});
const resonator=(effects:EffectDefinition[]=[]):Resonator=>({id:"r",name:"r",element:"fusion",weaponType:"sword",rarity:5,skillNames:{basicAttack:"a",resonanceSkill:"s",forteCircuit:"f",resonanceLiberation:"l",introSkill:"i"},resonanceChain:[],combat:{level10Only:true,forms:[],modes:[],resources:[],actions:[action("base"),action("enhanced",200),action("follow",50)],effects:effects.map((structuredEffect,i)=>({id:`e${i}`,name:`e${i}`,sourceId:"r",trigger:"structured",target:"self",effect:"structured",structuredEffect,source})),rotations:[],unknowns:[],source},source});
const def=(id:string,operations:TriggerOperation[]=[],extra:Partial<EffectDefinition>={}):EffectDefinition=>({id,label:id,source:{id,type:"system",label:id},target:"self",rules:[],triggers:operations.length?[{id:`${id}-trigger`,event:"action-start",operations}]:undefined,...extra});
const event=(ownerId="a",targetId="t",timestamp=0):CombatEvent=>({id:`${ownerId}:${targetId}:${timestamp}`,timestamp,kind:"action-start",ownerId,actorId:ownerId,targetId,actionId:"base"});
const ctx={panelStats:stats};

describe("consolidation State Engine",()=>{
 it("résout Effect A → activate Effect B avec le lifecycle et les rules de B",()=>{const b=def("B",[],{rules:[{id:"b-rule",label:"B rule",accounting:"runtime",modifiers:[{kind:"all-damage-bonus",stacking:"additive",value:10}]}],lifecycle:{duration:{kind:"fixed",seconds:4}}});const a=def("A",[{kind:"activate-effect",effectId:"B"}]);const r=processEvent(emptyCombatState({a:{}},["t"]),event(),[a,b],ctx);expect(r.state.activeEffects[0].definition).toBe(b);expect(r.state.activeEffects[0]).toMatchObject({expiresAt:4});expect(r.state.activeEffects[0].definition.rules[0].id).toBe("b-rule");});
 it("isole expire et stacks par owner pour un même effect id",()=>{const x=def("X",[],{lifecycle:{duration:{kind:"fixed",seconds:5},stacks:{kind:"shared",max:5}}});const trigger=def("T",[{kind:"gain-stacks",effectId:"X",amount:{kind:"constant",value:1}}]);const initial={...emptyCombatState({a:{},b:{}},["t"]),activeEffects:[{id:"a",definition:x,ownerId:"a",activatedAt:0,stacks:1},{id:"b",definition:x,ownerId:"b",activatedAt:0,stacks:3}]};const r=processEvent(initial,event("a"),[x,trigger],ctx);expect(r.state.activeEffects.map(e=>[e.ownerId,e.stacks])).toEqual([["a",2],["b",3]]);});
 it("isole un status identique sur deux targets",()=>{const s=def("S",[{kind:"apply-status",statusId:"mark",stacks:{kind:"constant",value:1}}],{statuses:[{id:"mark",label:"mark",maxStacks:5}]});let state=emptyCombatState({a:{}},["t1","t2"]);state=processEvent(state,event("a","t1"),[s],ctx).state;state=processEvent(state,{...event("a","t2"),id:"second"},[s],ctx).state;expect(state.targets.t1.statuses.mark.stacks).toBe(1);expect(state.targets.t2.statuses.mark.stacks).toBe(1);});
 it("expire indépendamment les stacks et consomme les plus anciennes",()=>{const x=def("X",[],{lifecycle:{duration:{kind:"fixed",seconds:5},stacks:{kind:"independent-expirations",max:3}}});const gain=def("G",[{kind:"gain-stacks",effectId:"X",amount:{kind:"constant",value:1}}]);let state:CombatState={...emptyCombatState({a:{}},["t"]),activeEffects:[{id:"x",definition:x,ownerId:"a",activatedAt:0,stacks:0,stackExpirations:[]}]};state=processEvent(state,event("a","t",0),[x,gain],ctx).state;state=processEvent(state,event("a","t",2),[x,gain],ctx).state;expect(advanceState(state,5).state.activeEffects[0].stackExpirations).toEqual([7]);expect(advanceState(state,7).state.activeEffects[0].stacks).toBe(0);});
 it("exécute refresh, extension bornée, no-reset-at-max et exclusive group",()=>{const x=def("X",[],{lifecycle:{duration:{kind:"fixed",seconds:5},refresh:"reset-duration",extension:{seconds:2,limitSeconds:8,maxExtensions:1},exclusiveGroup:"stance",stacks:{kind:"shared",max:1}}});const activate=def("A",[{kind:"activate-effect",effectId:"X"},{kind:"gain-stacks",effectId:"X",amount:{kind:"constant",value:1}}]);let state=processEvent(emptyCombatState({a:{}},["t"]),event("a","t",0),[x,activate],ctx).state;const extend=def("E",[{kind:"extend-effect",effectId:"X"}]);state=processEvent(state,event("a","t",1),[x,extend],ctx).state;state=processEvent(state,event("a","t",2),[x,extend],ctx).state;expect(state.activeEffects[0]).toMatchObject({expiresAt:7,extensionCount:1});const y=def("Y",[],{lifecycle:{duration:{kind:"indefinite"},exclusiveGroup:"stance"}}),ay=def("AY",[{kind:"activate-effect",effectId:"Y"}]);state=processEvent(state,event("a","t",3),[x,y,ay],ctx).state;expect(state.activeEffects.map(e=>e.definition.id)).toEqual(["Y"]);});
 it("refuse amounts inconnus pour status et ressources",()=>{const bad=def("bad",[{kind:"apply-status",statusId:"mark",stacks:{kind:"resource",resourceId:"missing"}},{kind:"resource",operation:"gain",resourceId:"gauge"}],{statuses:[{id:"mark",label:"mark",maxStacks:2}]});const state=emptyCombatState({a:{resources:{gauge:{current:0,max:5}}}},["t"]);const r=processEvent(state,event(),[bad],ctx);expect(r.diagnostics.map(d=>d.code)).toEqual(expect.arrayContaining(["invalid-status-stack-amount","missing-resource-amount"]));expect(r.state.targets.t.statuses.mark).toBeUndefined();});
 it("scope maxTriggers par owner",()=>{const once=def("once",[{kind:"enter-state",stateId:"on"}],{triggers:[{id:"same",event:"action-start",maxTriggers:1,triggerCountScope:"owner",operations:[{kind:"enter-state",stateId:"on"}]}]});let state=emptyCombatState({a:{},b:{}},["t"]);state=processEvent(state,event("a"),[once],ctx).state;state=processEvent(state,event("b"),[once],ctx).state;expect(state.actors.a.namedStates).toContain("on");expect(state.actors.b.namedStates).toContain("on");});
});

describe("consolidation Personal integration",()=>{
 const run=(effects:EffectDefinition[]=[],overrides:Partial<Parameters<typeof simulatePersonalCombat>[0]>={})=>simulatePersonalCombat({resonator:resonator(effects),build,timeline:timeline(),target:{level:90,elementalResistance:{fusion:0},physicalResistance:0},...overrides});
 it("charge automatiquement les structured effects du Resonator",()=>{const buff=def("buff",[],{rules:[{id:"r",label:"r",accounting:"runtime",modifiers:[{kind:"all-damage-bonus",stacking:"additive",value:20}]}]});const withBuff=run([buff]);expect(withBuff.personalDamage.expected).toBeGreaterThan(run().personalDamage.expected);expect(withBuff.audits[0].activeEffectIds).toContain("buff");});
 it("résout Weapon, Sonata, Echo et Sequence depuis la frontière loadout",()=>{const equipment=(id:string,type:"weapon"|"sonata"|"echo",requiredSequence=0)=>def(id,[],{source:{id,type,label:id},rules:[{id:`${id}-rule`,label:id,accounting:"runtime",requiredSequence,modifiers:[{kind:"all-damage-bonus",stacking:"additive",value:10}]}]});const weaponFx=equipment("weapon","weapon"),sonataFx=equipment("sonata","sonata"),echoFx=equipment("echo","echo"),sequenceFx=equipment("sequence","weapon",1);const weapon={id:"w",name:"w",type:"sword" as const,rarity:5 as const,effects:[{id:"w",name:"w",sourceId:"w",trigger:"structured",target:"self" as const,effect:"structured",structuredEffect:weaponFx,source}],source},sonata={id:"s",name:"s",effects:[{id:"s",name:"s",sourceId:"s",trigger:"structured",target:"self" as const,effect:"structured",structuredEffect:sonataFx,source}],source},mainEcho={id:"e",name:"e",sonataIds:[],effects:[{id:"e",name:"e",sourceId:"e",trigger:"structured",target:"self" as const,effect:"structured",structuredEffect:echoFx,source}],source};const r=run([],{loadout:{weapon,sonata,mainEcho,sequenceEffects:[sequenceFx]}});expect(r.audits[0].activeEffectIds).toEqual(expect.arrayContaining(["weapon","sonata","echo"]));expect(r.audits[0].activeEffectIds).not.toContain("sequence");const s1=run([],{build:{...build,sequence:1},loadout:{sequenceEffects:[sequenceFx]}});expect(s1.audits[0].activeEffectIds).toContain("sequence");});
 it("exécute action replacement puis damage type replacement et selectors",()=>{const replacements=def("replace",[],{rules:[{id:"replace",label:"replace",accounting:"runtime",modifiers:[{kind:"action-replacement",actionId:"base",replacementActionId:"enhanced",condition:{kind:"state-active",id:"powered"}},{kind:"damage-type-replacement",damageType:"resonanceLiberation",condition:{kind:"state-active",id:"powered"}}]}]});const initial={...emptyCombatState({r:{namedStates:["powered"]}},["target"])};const r=run([replacements],{initialState:initial});expect(r.audits[0]).toMatchObject({baseActionId:"base",actionId:"enhanced",baseDamageType:"basicAttack",effectiveDamageType:"resonanceLiberation"});expect(r.audits[0].damage.status).toBe("supported");});
 it("rend les timings manquants pertinents seulement pour un trigger on-hit",()=>{expect(run().partial).toBe(false);const onHit=def("hit",[{kind:"enter-state",stateId:"hit"}],{triggers:[{id:"hit",event:"action-hit",operations:[{kind:"enter-state",stateId:"hit"}]}]});expect(run([onHit]).unsupportedMechanics.map(x=>x.code)).toContain("hit-timing-required");const known=run([onHit],{timeline:timeline([.5])});expect(known.unsupportedMechanics.map(x=>x.code)).not.toContain("hit-timing-required");expect(known.finalState.actors.r.namedStates).toContain("hit");});
 it("émet damage-dealt depuis un vrai hit et permet une chaîne contrôlée",()=>{const chain=def("chain",[],{triggers:[{id:"after-damage",event:"damage-dealt",maxTriggers:1,operations:[{kind:"emit-action",action:{actionId:"follow",attribution:"follow-up",snapshot:{stats:"hit",stacks:"tick"}}}]}]});const r=run([chain],{timeline:timeline([.5])});expect(r.eventLog.some(e=>e.kind==="damage-dealt")).toBe(true);expect(r.breakdown["follow-up"].expected).toBeGreaterThan(0);});
 it("intègre apply status, ticks, dégâts, consommation, expiration et transformation",()=>{const status=def("status",[],{statuses:[{id:"dot",label:"dot",maxStacks:2,durationSeconds:2.5,periodic:{intervalSeconds:1,maxTicks:2,consumeStacks:1,emittedAction:{actionId:"follow",attribution:"status",snapshot:{stats:"hit",stacks:"tick"}}}},{id:"burst",label:"burst",maxStacks:1}],triggers:[{id:"apply",event:"action-start",maxTriggers:1,operations:[{kind:"apply-status",statusId:"dot",stacks:{kind:"constant",value:1}}]}]});const r=run([status]);expect(r.breakdown.status.expected).toBeGreaterThan(0);expect(r.eventLog.filter(e=>e.payload?.statusId==="dot")).toHaveLength(2);expect(r.finalState.targets.target.statuses.dot).toBeUndefined();const transform=def("transform",[],{statuses:[{id:"mark",label:"mark",maxStacks:2,transformAtMaxTo:"burst"},{id:"burst",label:"burst",maxStacks:1}],triggers:[{id:"apply",event:"action-start",operations:[{kind:"apply-status",statusId:"mark",stacks:{kind:"constant",value:2}}]}]});expect(run([transform]).finalState.targets.target.statuses.burst.stacks).toBe(1);});
 it("conserve actor/owner/scaling owner et refuse un scaling owner étranger",()=>{const summon:CombatEvent={id:"summon",timestamp:1,kind:"action-hit",ownerId:"r",actorId:"pet",sourceEntityId:"pet",triggeringActorId:"ally",targetId:"target",actionId:"follow",payload:{attribution:"summon",damageOwnerId:"r",scalingOwnerId:"r"}};const r=run([],{externalEvents:[summon]});expect(r.audits.find(a=>a.attribution==="summon")).toMatchObject({actorId:"pet",damageOwnerId:"r",scalingOwnerId:"r",sourceEntityId:"pet",triggeringActorId:"ally"});const foreign=run([],{externalEvents:[{...summon,id:"foreign",payload:{...summon.payload,scalingOwnerId:"other"}}]});expect(foreign.unsupportedMechanics.map(x=>x.code)).toContain("foreign-scaling-owner-unsupported");});
 it("exécute réellement snapshot trigger vs hit",()=>{const buff=def("buff",[],{rules:[{id:"atk",label:"atk",accounting:"runtime",modifiers:[{kind:"runtime-stat",stat:"attack",mode:"flat",stacking:"additive",value:{kind:"constant",value:500}}]}],lifecycle:{duration:{kind:"fixed",seconds:1}}});const emitter=(statsPolicy:"trigger"|"hit")=>def(`emit-${statsPolicy}`,[],{triggers:[{id:`emit-${statsPolicy}`,event:"action-start",maxTriggers:1,operations:[{kind:"emit-action",action:{actionId:"follow",delaySeconds:2,attribution:"follow-up",snapshot:{stats:statsPolicy,stacks:"tick"}}}]}]});const trigger=run([buff,emitter("trigger")]),hit=run([buff,emitter("hit")]);expect(trigger.breakdown["follow-up"].expected).toBeGreaterThan(hit.breakdown["follow-up"].expected);});
 it("applique un ICD à une coordinated attack externe sans compter les hits alliés",()=>{const coordinated=def("coordinated",[],{triggers:[{id:"ally-hit",event:"action-hit",externalContextRequired:true,cooldown:{seconds:1,scope:"target"},operations:[{kind:"emit-action",action:{actionId:"follow",attribution:"coordinated",snapshot:{stats:"hit",stacks:"tick"}}}]}]});const ally=(id:string,timestamp:number):CombatEvent=>({id,timestamp,kind:"action-hit",ownerId:"ally",actorId:"ally",targetId:"target",external:true});const r=run([coordinated],{externalEvents:[ally("a",.1),ally("b",.5),ally("c",1.2)]});expect(r.audits.filter(a=>a.attribution==="coordinated")).toHaveLength(2);expect(r.audits.some(a=>a.damageOwnerId==="ally")).toBe(false);});
 it("Effect A active B avant un hit puis B expire avant le hit suivant",()=>{const b=def("B",[],{rules:[{id:"bonus",label:"bonus",accounting:"runtime",modifiers:[{kind:"all-damage-bonus",stacking:"additive",value:100}]}],lifecycle:{duration:{kind:"fixed",seconds:1}}});const a=def("A",[],{triggers:[{id:"activate-b",event:"action-start",maxTriggers:1,operations:[{kind:"activate-effect",effectId:"B"}]}]});const two:TemporalTimeline={...timeline([.5]),finalDurationSeconds:3,rawDurationSeconds:3,measuredDurationSeconds:3,entries:[{...timeline([.5]).entries[0],endTimeSeconds:1},{...timeline([.5]).entries[0],index:1,stepId:"s2",startTimeSeconds:2,endTimeSeconds:3,hitTimingsSeconds:[.5]}]};const r=run([a,b],{timeline:two});const hits=r.audits.filter(audit=>audit.actionId==="base");expect(hits).toHaveLength(2);expect((hits[0].damage.status==="supported"&&hits[0].damage.total.expected)||(0)).toBeGreaterThan((hits[1].damage.status==="supported"&&hits[1].damage.total.expected)||(0));});
 it("préserve l'immutabilité des inputs",()=>{const r=resonator(),beforeStats=structuredClone(build.finalStats),beforeActions=structuredClone(r.combat!.actions);run([],{resonator:r});expect(build.finalStats).toEqual(beforeStats);expect(r.combat!.actions).toEqual(beforeActions);});
});
