import {buildEffectiveCombatStats,evaluatePredicate,evaluateValueExpression,type CombatContext,type RuntimeBaseStatBasis} from "./combat-context";
import {calculateActionDamage,calculateTuneBreakDamage,calculateTuneRuptureDamage,type DamageAmounts,type DamageTarget,type ScalingAttribute} from "./damage-engine";
import {resolveActiveEffects,type EffectAuditEntry} from "./effect-engine";
import type{ActionDefinitionV02,EffectDefinition,EffectModifier,FixedCritOverrideModifier,RuntimeStatModifier}from"./effect-models";
import {CombatEventQueue}from"./event-engine";
import type{CombatAction,FinalStats,MainEcho,Resonator,Sonata,UserBuild,Weapon}from"./models";
import{emptyCombatState,processEvent,timelineEvents,type CombatEvent,type CombatState,type StateDiagnostic,type StateTransition}from"./state-engine";
import type{TemporalTimeline}from"./temporal-engine";

export type DamageAttribution="direct"|"echo"|"follow-up"|"coordinated"|"summon"|"status"|"tune";
export interface PersonalDiagnostic{code:string;message:string;eventId?:string;actionId?:string;}
export interface PersonalDamageAudit{timestamp:number;eventId:string;actionId:string;damageOwnerId:string;scalingOwnerId:string;actorId:string;targetId:string;attribution:DamageAttribution;panelStats:FinalStats;baseStatBasis:RuntimeBaseStatBasis;effectiveStats:FinalStats;runtimeStatAudit:ReturnType<typeof buildEffectiveCombatStats>["audit"];originalMotionValue:number;motionValueContributions:readonly{mode:string;value:number;effectId:string}[];effectiveMotionValue:number;activeEffectIds:readonly string[];effectAudit:readonly EffectAuditEntry[];damage:ReturnType<typeof calculateActionDamage>;sourceEffectId?:string;}
export interface Coverage{timelineSteps:number;directDamageActions:number;derivedActions:number;activeEffects:number;triggeredEffects:number;unsupportedDamageEvents:number;unresolvedConditions:number;externalTriggerRequirements:number;notEmitted:number;}
export interface PersonalCombatResult{rotationDurationSeconds:number;personalDamage:DamageAmounts;personalDps:DamageAmounts;breakdown:Readonly<Record<DamageAttribution,DamageAmounts>>;perAction:Readonly<Record<string,DamageAmounts>>;perSource:Readonly<Record<string,DamageAmounts>>;audits:readonly PersonalDamageAudit[];eventLog:readonly CombatEvent[];stateTransitions:readonly StateTransition[];stateDiagnostics:readonly StateDiagnostic[];diagnostics:readonly PersonalDiagnostic[];unsupportedMechanics:readonly PersonalDiagnostic[];coverage:Coverage;partial:boolean;finalState:CombatState;}
export interface PersonalEffectLoadout{resonatorEffects?:readonly EffectDefinition[];sequenceEffects?:readonly EffectDefinition[];weapon?:Weapon;sonata?:Sonata;mainEcho?:MainEcho;extraEffects?:readonly EffectDefinition[];ownedEntityIds?:readonly string[];}
export interface PersonalCombatRequest{resonator:Resonator;build:UserBuild;timeline:TemporalTimeline;target:DamageTarget&{id?:string;tuneEnemyClass?:"1C"|"3C"|"4C"};resonanceMode?:string;scalingAttribute?:ScalingAttribute;baseStatBasis?:RuntimeBaseStatBasis;actions?:readonly(ActionDefinitionV02|CombatAction)[];loadout?:PersonalEffectLoadout;initialState?:CombatState;externalEvents?:readonly CombatEvent[];}

export function loadPersonalEffects(ownerId:string,sequence:number,loadout:PersonalEffectLoadout={}):{definitions:EffectDefinition[];audit:{effectId:string;source:string;accounting:string}[];diagnostics:PersonalDiagnostic[]}{const candidates=[...(loadout.resonatorEffects??[]),...(loadout.sequenceEffects??[]),...(loadout.weapon?.effects??[]).flatMap(x=>x.structuredEffect?[x.structuredEffect]:[]),...(loadout.sonata?.effects??[]).flatMap(x=>x.structuredEffect?[x.structuredEffect]:[]),...(loadout.mainEcho?.effects??[]).flatMap(x=>x.structuredEffect?[x.structuredEffect]:[]),...(loadout.extraEffects??[])];const definitions:EffectDefinition[]=[],audit:{effectId:string;source:string;accounting:string}[]=[],diagnostics:PersonalDiagnostic[]=[];for(const definition of candidates){const rules=definition.rules.filter(r=>(r.requiredSequence??0)<=sequence);if(!rules.length)continue;const d={...definition,rules};definitions.push(d);for(const rule of rules)audit.push({effectId:d.id,source:d.source.type,accounting:rule.accounting});}void ownerId;return{definitions,audit,diagnostics};}

const zero=():DamageAmounts=>({nonCrit:0,crit:0,expected:0});const add=(a:DamageAmounts,b:DamageAmounts):DamageAmounts=>({nonCrit:a.nonCrit+b.nonCrit,crit:a.crit+b.crit,expected:a.expected+b.expected});
export function simulatePersonalCombat(req:PersonalCombatRequest):PersonalCombatResult{
 const targetId=req.target.id??"target";const actions=new Map<string,ActionDefinitionV02>();for(const x of req.actions??req.resonator.combat?.actions??[]){const d="action"in x?x:{action:x};actions.set(d.action.id,d);}if(req.loadout?.mainEcho?.action)actions.set(req.loadout.mainEcho.action.id,{action:req.loadout.mainEcho.action});
 const loaded=loadPersonalEffects(req.resonator.id,req.build.sequence,req.loadout);const initial=req.initialState??emptyCombatState({[req.resonator.id]:{hp:req.build.finalStats.hp,maxHp:req.build.finalStats.hp,onField:true,resources:Object.fromEntries((req.resonator.combat?.resources??[]).map(r=>[r.id,{current:0,max:r.cap}]))}},[targetId]);let state:CombatState={...initial,activeEffects:[...initial.activeEffects,...loaded.definitions.filter(d=>!d.triggers?.length&&d.rules.some(r=>r.accounting==="runtime")).map(d=>({id:`initial:${d.id}`,definition:d,ownerId:req.resonator.id,activatedAt:0}))]};
 const timeline=timelineEvents(req.timeline.entries,req.resonator.id,targetId),q=new CombatEventQueue(),diagnostics:PersonalDiagnostic[]=[...timeline.diagnostics,...loaded.diagnostics];for(const e of[...timeline.events,...(req.externalEvents??[])])q.enqueue(e);for(const d of loaded.definitions)for(const t of d.triggers??[])if(t.externalContextRequired&&!(req.externalEvents??[]).some(e=>e.kind===t.event&&e.external))diagnostics.push({code:"external-trigger-context-required",message:`${t.id} has no external trigger event.`});
 const audits:PersonalDamageAudit[]=[],transitions:StateTransition[]=[],stateDiagnostics:StateDiagnostic[]=[];const breakdown=Object.fromEntries((["direct","echo","follow-up","coordinated","summon","status","tune"]as const).map(k=>[k,zero()]))as Record<DamageAttribution,DamageAmounts>;const perAction:Record<string,DamageAmounts>={},perSource:Record<string,DamageAmounts>={};let triggered=0;
 const queueResult=q.drain(event=>{const derived:CombatEvent[]=[];const sr=processEvent(state,event,loaded.definitions,{panelStats:req.build.finalStats,resonanceMode:req.resonanceMode,element:req.resonator.element});state=sr.state;derived.push(...sr.emittedEvents.map(e=>e.kind==="action-hit"?{...e,ownerId:req.resonator.id,payload:{...e.payload,damageOwnerId:e.payload?.damageOwnerId??req.resonator.id,scalingOwnerId:e.payload?.scalingOwnerId??req.resonator.id}}:e));transitions.push(...sr.transitions);stateDiagnostics.push(...sr.diagnostics);triggered+=sr.transitions.filter(t=>t.kind==="effect-activated").length;
   const shouldDamage=event.kind==="action-hit"||event.kind==="tune-break"||event.kind==="tune-rupture"||event.kind==="fusion-burst"||(event.kind==="action-start"&&!event.originEventId);if(!shouldDamage||!event.actionId||event.external)return derived;const def=actions.get(event.actionId);if(!def){diagnostics.push({code:"action-not-found",message:`Action ${event.actionId} is not available.`,eventId:event.id,actionId:event.actionId});return derived;}const talentLevel=req.build.skillLevels[def.action.talent as keyof typeof req.build.skillLevels];let action=def.action;if(talentLevel!==undefined&&talentLevel!==action.level){const exact=def.multipliersByTalentLevel?.[talentLevel];if(!exact){diagnostics.push({code:"missing-exact-talent-multiplier",message:`No exact Lv${talentLevel} multiplier for ${action.id}.`,eventId:event.id,actionId:action.id});return derived;}action={...action,level:talentLevel as 10,multipliers:exact};}
   if(def.requirements){const ctx0=contextFor(event,req,state,targetId,req.build.finalStats);const prs=def.requirements.map(p=>evaluatePredicate(p,ctx0));if(prs.some(p=>p.status==="unsupported")){diagnostics.push({code:"unresolved-condition",message:`Requirement unresolved for ${action.id}.`,eventId:event.id,actionId:action.id});return derived;}if(prs.some(p=>p.status==="ignored"))return derived;}else if(action.requiredState?.length){diagnostics.push({code:"unstructured-requirement",message:`Legacy requirements are not executable for ${action.id}.`,eventId:event.id,actionId:action.id});return derived;}
   const active=state.activeEffects.filter(e=>e.ownerId===req.resonator.id);const ctx=contextFor(event,req,state,targetId,req.build.finalStats);const runtime: {stat:RuntimeStatModifier["stat"];mode:RuntimeStatModifier["mode"];value:number}[]=[];const mv:{mode:string;value:number;effectId:string}[]=[];for(const inst of active)for(const rule of inst.definition.rules){if(rule.accounting!=="runtime"||(rule.predicates??[]).some(p=>evaluatePredicate(p,ctx).status!=="matched"))continue;for(const m of rule.modifiers){if(m.kind==="runtime-stat"){const r=evaluateValueExpression(m.value,ctx,{stacks:inst.stacks,rank:inst.rank??req.build.weapon.rank});if(r.status==="supported")runtime.push({stat:m.stat,mode:m.mode,value:r.value!});else diagnostics.push({code:r.diagnostics[0]?.code??"invalid-expression",message:r.diagnostics[0]?.message??"Runtime stat expression unsupported.",eventId:event.id});}if(m.kind==="motion-value"){const r=evaluateValueExpression(m.value,ctx,{stacks:inst.stacks,rank:inst.rank??req.build.weapon.rank});if(r.status==="supported")mv.push({mode:m.mode,value:r.value!,effectId:inst.definition.id});}}}
   const effective=buildEffectiveCombatStats(req.build.finalStats,req.baseStatBasis??{},runtime);if(effective.status==="unsupported"){for(const d of effective.diagnostics)diagnostics.push({code:d.split(":")[0],message:d,eventId:event.id,actionId:action.id});return derived;}const original=action.multipliers.reduce((s,g)=>s+g.percent*g.hits,0);const additive=mv.filter(x=>x.mode==="additive-percent").reduce((s,x)=>s+x.value,0),mult=mv.filter(x=>x.mode==="multiplier").reduce((s,x)=>s*x.value/100,1);const factor=original===0?1:(original+additive)/original*mult;const effectiveAction=mv.length?{...action,multipliers:action.multipliers.map(g=>({...g,percent:g.percent*factor}))}:action;
   const legacyInstances=active.map(i=>({...i,definition:{...i.definition,rules:i.definition.rules.map(r=>({...r,modifiers:r.modifiers.filter(m=>!["runtime-stat","motion-value","action-replacement","damage-type-replacement"].includes(m.kind)) as readonly(EffectModifier|FixedCritOverrideModifier)[]}))}}));const resolved=resolveActiveEffects(legacyInstances,{actorId:event.actorId,targetId,teamMemberIds:[req.resonator.id],element:req.resonator.element,damageType:action.damageType&&action.damageType!=="tuneRupture"?action.damageType:undefined,resonanceMode:req.resonanceMode,actionId:action.id});
   let damage:ReturnType<typeof calculateActionDamage>;if(event.kind==="tune-break"&&req.target.tuneEnemyClass)damage=calculateTuneBreakDamage({finalStats:effective.stats,attackerLevel:req.build.characterLevel,enemyClass:req.target.tuneEnemyClass,target:req.target,modifiers:resolved.tuneDamageModifiers}) as ReturnType<typeof calculateActionDamage>;else if((event.kind==="tune-rupture"||action.damageType==="tuneRupture")&&req.target.tuneEnemyClass)damage=calculateTuneRuptureDamage({action:effectiveAction,finalStats:effective.stats,attackerLevel:req.build.characterLevel,enemyClass:req.target.tuneEnemyClass,element:req.resonator.element,target:req.target,modifiers:resolved.tuneDamageModifiers,critOverride:resolved.overrides.fixedCrit}) as ReturnType<typeof calculateActionDamage>;else if(event.kind==="fusion-burst"){diagnostics.push({code:"formula-not-supported",message:"Fusion Burst damage formula is not verified.",eventId:event.id,actionId:action.id});return derived;}else damage=calculateActionDamage({action:effectiveAction,finalStats:effective.stats,attackerLevel:req.build.characterLevel,scalingAttribute:req.scalingAttribute??"attack",element:req.resonator.element,target:req.target,modifiers:resolved.damageModifiers});if(damage.status==="unsupported"){diagnostics.push({code:damage.reason,message:damage.message,eventId:event.id,actionId:action.id});return derived;}
   const payload=event.payload??{};const attribution=(payload.attribution as DamageAttribution|undefined)??(action.talent==="echoSkill"?"echo":"direct");const damageOwner=(payload.damageOwnerId as string|undefined)??event.ownerId;if(damageOwner!==req.resonator.id&&!(req.loadout?.ownedEntityIds??[]).includes(damageOwner))return derived;breakdown[attribution]=add(breakdown[attribution],damage.total);perAction[action.id]=add(perAction[action.id]??zero(),damage.total);const source=(payload.sourceEffectId as string|undefined)??(attribution==="direct"?req.resonator.id:attribution);perSource[source]=add(perSource[source]??zero(),damage.total);audits.push({timestamp:event.timestamp,eventId:event.id,actionId:action.id,damageOwnerId:damageOwner,scalingOwnerId:(payload.scalingOwnerId as string|undefined)??req.resonator.id,actorId:event.actorId,targetId,attribution,panelStats:req.build.finalStats,baseStatBasis:req.baseStatBasis??{},effectiveStats:effective.stats,runtimeStatAudit:effective.audit,originalMotionValue:original,motionValueContributions:mv,effectiveMotionValue:effectiveAction.multipliers.reduce((s,g)=>s+g.percent*g.hits,0),activeEffectIds:active.map(e=>e.definition.id),effectAudit:resolved.audit,damage,sourceEffectId:payload.sourceEffectId as string|undefined});return derived;});
 diagnostics.push(...queueResult.diagnostics.map(d=>({code:d.code,message:d.message,eventId:d.eventId})));const personalDamage=Object.values(breakdown).reduce(add,zero()),duration=req.timeline.finalDurationSeconds,personalDps:{nonCrit:number;crit:number;expected:number}=duration>0?{nonCrit:personalDamage.nonCrit/duration,crit:personalDamage.crit/duration,expected:personalDamage.expected/duration}:zero();const unsupported=diagnostics.filter(d=>!["hit-timing-required"].includes(d.code));const coverage:Coverage={timelineSteps:req.timeline.entries.length,directDamageActions:audits.filter(a=>a.attribution==="direct").length,derivedActions:audits.filter(a=>a.attribution!=="direct").length,activeEffects:state.activeEffects.length,triggeredEffects:triggered,unsupportedDamageEvents:unsupported.length,unresolvedConditions:diagnostics.filter(d=>d.code.includes("condition")||d.code.includes("requirement")).length,externalTriggerRequirements:diagnostics.filter(d=>d.code==="external-trigger-context-required").length,notEmitted:0};return{rotationDurationSeconds:duration,personalDamage,personalDps,breakdown,perAction,perSource,audits,eventLog:queueResult.processed,stateTransitions:transitions,stateDiagnostics,diagnostics,unsupportedMechanics:unsupported,coverage,partial:unsupported.length>0||queueResult.partial,finalState:state};}

function contextFor(event:CombatEvent,req:PersonalCombatRequest,state:CombatState,targetId:string,panel:FinalStats):CombatContext{const actor=state.actors[event.ownerId],target=state.targets[targetId];return{timestamp:event.timestamp,actorId:event.actorId,ownerId:event.ownerId,targetId,sourceId:event.sourceId,damageOwnerId:event.payload?.damageOwnerId as string|undefined,scalingOwnerId:event.payload?.scalingOwnerId as string|undefined,actionId:event.actionId,eventKind:event.kind,eventSourceId:event.sourceId,eventTargetId:targetId,element:req.resonator.element,resonanceMode:req.resonanceMode,panelStats:panel,resources:actor?.resources,states:actor?.namedStates,form:actor?.form,onField:actor?.onField,actorHpRatio:actor?.hp!==undefined&&actor.maxHp?actor.hp/actor.maxHp:undefined,targetHpRatio:target?.hp!==undefined&&target.maxHp?target.hp/target.maxHp:undefined,targetStatuses:Object.fromEntries(Object.entries(target?.statuses??{}).map(([k,v])=>[k,v.stacks])),activeEffectIds:state.activeEffects.map(e=>e.definition.id)};}
