import {describe,expect,it} from "vitest";
import {advanceState,applyResource,cooldownKey,emptyCombatState,processEvent,timelineEvents,type CombatEvent} from "./state-engine";
import type {EffectDefinition} from "./effect-models";
import type {FinalStats} from "./models";
const panel:FinalStats={hp:1,attack:1,defense:1,critRate:0,critDamage:100,energyRegen:100,healingBonus:0,tuneBreakBoost:0,elementalDamageBonus:{aero:0,glacio:0,electro:0,fusion:0,havoc:0,spectro:0},damageTypeBonus:{basicAttack:0,heavyAttack:0,resonanceSkill:0,resonanceLiberation:0,introSkill:0,echoSkill:0}};
const event:CombatEvent={id:"e",timestamp:1,kind:"action-start",ownerId:"a",actorId:"a",targetId:"t",actionId:"x"};
const effect:EffectDefinition={id:"buff",label:"Buff",source:{id:"fixture",type:"system",label:"Fixture"},target:"self",rules:[],statuses:[{id:"mark",label:"Mark",maxStacks:3}],lifecycle:{duration:{kind:"fixed",seconds:2},refresh:"reset-duration",stacks:{kind:"shared",max:3}},triggers:[{id:"trigger",event:"action-start",cooldown:{seconds:1,scope:"action-target"},operations:[{kind:"activate-effect",effectId:"buff"},{kind:"gain-stacks",effectId:"buff",amount:{kind:"constant",value:1}},{kind:"resource",operation:"gain",resourceId:"gauge",amount:{kind:"constant",value:2}},{kind:"apply-status",statusId:"mark",stacks:{kind:"constant",value:2}},{kind:"enter-state",stateId:"powered"}]}]};
describe("State Engine V0.1",()=>{
 it("gère activation, durée, stacks, ressources, états, target status et cooldown",()=>{const initial=emptyCombatState({a:{resources:{gauge:{current:1,max:5}}}},["t"]);const r=processEvent(initial,event,[effect],{panelStats:panel});expect(r.state.activeEffects[0]).toMatchObject({stacks:1,expiresAt:3});expect(r.state.actors.a.resources.gauge.current).toBe(3);expect(r.state.actors.a.namedStates).toContain("powered");expect(r.state.targets.t.statuses.mark.stacks).toBe(2);expect(Object.keys(r.state.cooldowns)[0]).toContain("action-target:x:t");expect(advanceState(r.state,3).state.activeEffects).toHaveLength(0);});
 it("respecte le no-refresh-at-max",()=>{const d={...effect,lifecycle:{...effect.lifecycle!,refresh:"no-reset-at-max-stacks" as const},triggers:[]};const s={...emptyCombatState({a:{}},["t"]),activeEffects:[{id:"i",definition:d,ownerId:"a",activatedAt:0,expiresAt:2,stacks:3}]};const r=processEvent(s,event,[{...d,triggers:[{id:"x",event:"action-start",operations:[{kind:"activate-effect",effectId:"buff"}]}]}],{panelStats:panel});expect(r.state.activeEffects[0].expiresAt).toBe(2);});
 it("produit des clés ICD déterministes",()=>{expect(cooldownKey("target",event,"q")).toBe("target:t:q");expect(cooldownKey("action-target",event,"q")).toBe("action-target:x:t:q");});
 it("clamp les ressources",()=>{expect(applyResource({current:4,max:5},"gain",10).current).toBe(5);expect(applyResource({current:2,max:5},"consume-up-to",9).current).toBe(0);});
 it("n'invente aucun hit timing",()=>{const r=timelineEvents([{stepId:"s",actionId:"x",startTimeSeconds:0,endTimeSeconds:1,hitTimingsSeconds:null}],"a","t");expect(r.events.some(e=>e.kind==="action-hit")).toBe(false);expect(r.missingHitTimings).toEqual(["s"]);});
 it("ne traite pas une transition théorique comme un hit manquant",()=>{const r=timelineEvents([{stepId:"transition",startTimeSeconds:0,endTimeSeconds:.25,hitTimingsSeconds:null}],"a","t");expect(r.events.some(e=>e.kind==="action-hit")).toBe(false);expect(r.missingHitTimings).toEqual([]);});
 it("isole les owners",()=>{const s=emptyCombatState({a:{},b:{}},["t"]);const r=processEvent(s,{...event,ownerId:"b",actorId:"b"},[effect],{panelStats:panel});expect(r.state.activeEffects[0].ownerId).toBe("b");});
});
