import { evaluatePredicate, evaluateValueExpression, type CombatContext, type ResourceView } from "./combat-context";
import type { ActiveEffectInstance, CombatEventKind, EffectDefinition, StatusDefinition, TriggerOperation } from "./effect-models";

export interface CombatEvent { id:string; timestamp:number; kind:CombatEventKind; ownerId:string; actorId:string; targetId:string; sourceId?:string; actionId?:string; element?:string; external?:boolean; originEventId?:string; depth?:number; payload?:Readonly<Record<string,unknown>>; }
export interface ActiveRuntimeEffect extends ActiveEffectInstance { activatedAt:number; expiresAt?:number; stackExpirations?:readonly number[]; }
export interface ActorState { hp?:number; maxHp?:number; shield?:number; onField?:boolean; form?:string; namedStates:readonly string[]; resources:Readonly<Record<string,ResourceView>>; }
export interface TargetState { hp?:number; maxHp?:number; shield?:number; statuses:Readonly<Record<string,{stacks:number;expiresAt?:number;definition?:StatusDefinition}>>; marks:Readonly<Record<string,number>>; }
export interface CombatState { time:number; actors:Readonly<Record<string,ActorState>>; targets:Readonly<Record<string,TargetState>>; activeEffects:readonly ActiveRuntimeEffect[]; cooldowns:Readonly<Record<string,number>>; triggerCounters:Readonly<Record<string,number>>; registries:Readonly<Record<string,readonly string[]>>; }
export interface StateDiagnostic { code:string; message:string; eventId?:string; triggerId?:string; }
export interface StateTransition { timestamp:number; kind:string; detail:string; eventId?:string; }
export interface StateResult { state:CombatState; emittedEvents:readonly CombatEvent[]; transitions:readonly StateTransition[]; diagnostics:readonly StateDiagnostic[]; }

export const emptyCombatState=(actors:Readonly<Record<string,Partial<ActorState>>>={},targets:readonly string[]=[]):CombatState=>({time:0,actors:Object.fromEntries(Object.entries(actors).map(([id,a])=>[id,{namedStates:[],resources:{},...a}])),targets:Object.fromEntries(targets.map(id=>[id,{statuses:{},marks:{}}])),activeEffects:[],cooldowns:{},triggerCounters:{},registries:{}});

export function cooldownKey(scope:string,event:CombatEvent,triggerId:string,custom?:string):string|undefined { switch(scope){case"global":return`global:${triggerId}`;case"owner":return`owner:${event.ownerId}:${triggerId}`;case"source":return event.sourceId&&`source:${event.sourceId}:${triggerId}`;case"action":return event.actionId&&`action:${event.actionId}:${triggerId}`;case"target":return`target:${event.targetId}:${triggerId}`;case"action-target":return event.actionId&&`action-target:${event.actionId}:${event.targetId}:${triggerId}`;case"source-target":return event.sourceId&&`source-target:${event.sourceId}:${event.targetId}:${triggerId}`;case"element":return event.element&&`element:${event.element}:${triggerId}`;case"custom":return custom&&`custom:${custom}`;default:return undefined;} }
export function applyResource(view:ResourceView,operation:"gain"|"consume"|"set"|"set-max"|"consume-all"|"consume-up-to",amount?:number):ResourceView {if(!Number.isFinite(view.current)||!Number.isFinite(view.max)||view.max<=0||view.current<0||view.current>view.max)throw new Error("invalid-resource-state");if(amount!==undefined&&(!Number.isFinite(amount)||amount<0))throw new Error("invalid-resource-amount");let current=view.current;switch(operation){case"gain":current+=amount!;break;case"consume":current-=amount!;break;case"set":current=amount!;break;case"set-max":current=view.max;break;case"consume-all":current=0;break;case"consume-up-to":current-=Math.min(current,amount!);break;}return{current:Math.min(view.max,Math.max(0,current)),max:view.max};}

export function advanceState(input:CombatState,time:number):StateResult {if(!Number.isFinite(time)||time<input.time)throw new Error("invalid-state-time");const expired=input.activeEffects.filter(e=>e.expiresAt!==undefined&&e.expiresAt<=time);return{state:{...input,time,activeEffects:input.activeEffects.filter(e=>e.expiresAt===undefined||e.expiresAt>time).map(e=>e.stackExpirations?{...e,stackExpirations:e.stackExpirations.filter(x=>x>time),stacks:e.stackExpirations.filter(x=>x>time).length}:e),cooldowns:Object.fromEntries(Object.entries(input.cooldowns).filter(([,v])=>v>time))},emittedEvents:[],transitions:expired.map(e=>({timestamp:e.expiresAt!,kind:"effect-expired",detail:e.definition.id})),diagnostics:[]};}

export function processEvent(input:CombatState,event:CombatEvent,definitions:readonly EffectDefinition[],baseContext:Omit<CombatContext,"timestamp"|"actorId"|"ownerId"|"targetId">):StateResult {
  let state=advanceState(input,event.timestamp).state;const transitions:StateTransition[]=[],diagnostics:StateDiagnostic[]=[],emittedEvents:CombatEvent[]=[];
  const actor=state.actors[event.ownerId];const target=state.targets[event.targetId];const context:CombatContext={...baseContext,timestamp:event.timestamp,actorId:event.actorId,ownerId:event.ownerId,targetId:event.targetId,sourceId:event.sourceId,actionId:event.actionId,eventKind:event.kind,eventSourceId:event.sourceId,eventTargetId:event.targetId,actorHpRatio:actor?.hp!==undefined&&actor.maxHp?actor.hp/actor.maxHp:undefined,targetHpRatio:target?.hp!==undefined&&target.maxHp?target.hp/target.maxHp:undefined,onField:actor?.onField,shieldActive:(actor?.shield??0)>0,form:actor?.form,states:actor?.namedStates,resources:actor?.resources,targetStatuses:Object.fromEntries(Object.entries(target?.statuses??{}).map(([k,v])=>[k,v.stacks])),activeEffectIds:state.activeEffects.map(e=>e.definition.id)};
  for(const definition of definitions)for(const trigger of definition.triggers??[]){if(trigger.event!==event.kind)continue;if(trigger.externalContextRequired&&!event.external){diagnostics.push({code:"external-trigger-context-required",message:`${trigger.id} requires an external event.`,eventId:event.id,triggerId:trigger.id});continue;}const predicates=(trigger.predicates??[]).map(p=>evaluatePredicate(p,context));if(predicates.some(p=>p.status==="unsupported")){diagnostics.push({code:"unresolved-condition",message:`Predicate context missing for ${trigger.id}.`,eventId:event.id,triggerId:trigger.id});continue;}if(predicates.some(p=>p.status==="ignored"))continue;const count=state.triggerCounters[trigger.id]??0;if(count>=(trigger.maxTriggers??Infinity))continue;const key=trigger.cooldown&&cooldownKey(trigger.cooldown.scope,event,trigger.id,trigger.cooldown.customKey);if(trigger.cooldown&&!key){diagnostics.push({code:"cooldown-context-required",message:`Cannot build cooldown key for ${trigger.id}.`,eventId:event.id,triggerId:trigger.id});continue;}if(key&&(state.cooldowns[key]??0)>event.timestamp)continue;for(const op of trigger.operations){const result=applyOperation(state,event,definition,op,context);state=result.state;transitions.push(...result.transitions);emittedEvents.push(...result.events);diagnostics.push(...result.diagnostics);}state={...state,triggerCounters:{...state.triggerCounters,[trigger.id]:count+1},cooldowns:key?{...state.cooldowns,[key]:event.timestamp+trigger.cooldown!.seconds}:state.cooldowns};}
  return{state,emittedEvents,transitions,diagnostics};
}

function applyOperation(state:CombatState,event:CombatEvent,definition:EffectDefinition,op:TriggerOperation,context:CombatContext):{state:CombatState;events:CombatEvent[];transitions:StateTransition[];diagnostics:StateDiagnostic[]}{const transitions:StateTransition[]=[],events:CombatEvent[]=[],diagnostics:StateDiagnostic[]=[];const amount=(v:Exclude<TriggerOperation,{kind:"gain-stacks"|"consume-stacks"}> extends never?never:unknown)=>v;void amount;
  if(op.kind==="activate-effect"||op.kind==="refresh-effect"){const existing=state.activeEffects.find(e=>e.definition.id===op.effectId&&e.ownerId===event.ownerId);const life=definition.lifecycle;const expires=life?.duration.kind==="fixed"?event.timestamp+life.duration.seconds:undefined;if(existing){if(life?.refresh==="no-refresh"||(life?.refresh==="no-reset-at-max-stacks"&&existing.stacks===(life.stacks?.max??Infinity)))return{state,events,transitions,diagnostics};state={...state,activeEffects:state.activeEffects.map(e=>e===existing?{...e,expiresAt:expires}:e)};}else state={...state,activeEffects:[...state.activeEffects,{id:`${definition.id}:${event.ownerId}`,definition,ownerId:event.ownerId,sourceId:event.sourceId,stacks:life?.stacks?.initial??0,activatedAt:event.timestamp,expiresAt:expires}]};transitions.push({timestamp:event.timestamp,kind:"effect-activated",detail:op.effectId,eventId:event.id});}
  else if(op.kind==="expire-effect"){state={...state,activeEffects:state.activeEffects.filter(e=>e.definition.id!==op.effectId)};transitions.push({timestamp:event.timestamp,kind:"effect-expired",detail:op.effectId});}
  else if(op.kind==="gain-stacks"||op.kind==="consume-stacks"){const r=op.amount==="all"?undefined:evaluateValueExpression(op.amount,context);if(r?.status==="unsupported"){diagnostics.push({code:"invalid-stack-amount",message:"Stack amount unresolved."});return{state,events,transitions,diagnostics};}state={...state,activeEffects:state.activeEffects.map(e=>{if(e.definition.id!==op.effectId)return e;const max=e.definition.lifecycle?.stacks?.max??Infinity;const stacks=op.kind==="gain-stacks"?Math.min(max,(e.stacks??0)+r!.value!):op.amount==="all"?0:Math.max(0,(e.stacks??0)-r!.value!);return{...e,stacks};})};transitions.push({timestamp:event.timestamp,kind:op.kind,detail:op.effectId});}
  else if(op.kind==="resource"){const actor=state.actors[event.ownerId];const view=actor?.resources[op.resourceId];if(!actor||!view){diagnostics.push({code:"missing-resource",message:op.resourceId});return{state,events,transitions,diagnostics};}const r=op.amount&&evaluateValueExpression(op.amount,context);if(r?.status==="unsupported"){diagnostics.push({code:"missing-resource-amount",message:op.resourceId});return{state,events,transitions,diagnostics};}const next=applyResource(view,op.operation,r?.value);state={...state,actors:{...state.actors,[event.ownerId]:{...actor,resources:{...actor.resources,[op.resourceId]:next}}}};transitions.push({timestamp:event.timestamp,kind:`resource-${op.operation}`,detail:op.resourceId});}
  else if(op.kind==="enter-state"||op.kind==="exit-state"||op.kind==="change-form"){const actor=state.actors[event.ownerId];if(actor){state={...state,actors:{...state.actors,[event.ownerId]:op.kind==="change-form"?{...actor,form:op.stateId}:{...actor,namedStates:op.kind==="enter-state"?[...new Set([...actor.namedStates,op.stateId])]:actor.namedStates.filter(x=>x!==op.stateId)}}};}transitions.push({timestamp:event.timestamp,kind:op.kind,detail:op.stateId});}
  else if(op.kind==="apply-status"||op.kind==="remove-status"){const id=op.targetId??event.targetId;const target=state.targets[id]??{statuses:{},marks:{}};const r=op.stacks&&evaluateValueExpression(op.stacks,context);const statuses={...target.statuses};if(op.kind==="remove-status")delete statuses[op.statusId];else statuses[op.statusId]={stacks:r?.value??1};state={...state,targets:{...state.targets,[id]:{...target,statuses}}};transitions.push({timestamp:event.timestamp,kind:op.kind,detail:op.statusId});}
  else if(op.kind==="emit-event")events.push({...event,id:`${event.id}:${events.length}`,timestamp:event.timestamp+op.delaySeconds,kind:op.eventKind,originEventId:event.id,depth:(event.depth??0)+1,external:false});
  else if(op.kind==="emit-action")events.push({...event,id:`${event.id}:action:${op.action.actionId}:${events.length}`,timestamp:event.timestamp+(op.action.delaySeconds??0),kind:"action-hit",actorId:op.action.actorId??event.ownerId,actionId:op.action.actionId,originEventId:event.id,depth:(event.depth??0)+1,external:false,payload:{...op.action}});
  return{state,events,transitions,diagnostics};}

export function timelineEvents(entries:readonly {stepId:string;actionId?:string;startTimeSeconds:number;endTimeSeconds:number;hitTimingsSeconds:readonly number[]|null}[],ownerId:string,targetId:string):{events:CombatEvent[];diagnostics:StateDiagnostic[]}{const events:CombatEvent[]=[],diagnostics:StateDiagnostic[]=[];for(const [i,e]of entries.entries()){events.push({id:`rotation:${i}`,timestamp:e.startTimeSeconds,kind:"rotation-step-start",ownerId,actorId:ownerId,targetId,actionId:e.actionId},{id:`start:${i}`,timestamp:e.startTimeSeconds,kind:"action-start",ownerId,actorId:ownerId,targetId,actionId:e.actionId},{id:`end:${i}`,timestamp:e.endTimeSeconds,kind:"action-end",ownerId,actorId:ownerId,targetId,actionId:e.actionId});if(e.hitTimingsSeconds)for(const [h,t]of e.hitTimingsSeconds.entries())events.push({id:`hit:${i}:${h}`,timestamp:e.startTimeSeconds+t,kind:"action-hit",ownerId,actorId:ownerId,targetId,actionId:e.actionId});else diagnostics.push({code:"hit-timing-required",message:`No action-hit emitted for ${e.stepId}.`});}return{events,diagnostics};}
