import { describe, expect, it } from "vitest";
import { aemeath, aemeathPreset } from "@/data/aemeath";
import { chisa, chisaPreset, kumokiri, threadOfSeveredFate, threnodianLeviathan } from "@/data/chisa";
import { fallacyOfNoReturn, photosynthesisResponse, rejuvenatingGlow, variation, verina, verinaOutroAmplificationEffect, verinaPhotosynthesisEffect, verinaPreset } from "@/data/verina";
import type { RecommendedBuildPreset, UserBuild } from "./models";
import { activateTeamEffect, applyTeamTargetStatus, createTeamState, simulateTeam, type TeamActorInput } from "./team-engine";
import { bindTeamActorRuntime, discoverTeamIntroActions, resolveTeamActorAction } from "./team-runtime-binding";

const target = { level: 90, elementalResistance: { fusion: 0, havoc: 0, spectro: 0 }, physicalResistance: 0 };
function build(preset: RecommendedBuildPreset, id: string): UserBuild { return { ...preset, id, sourcePresetId: preset.id, skillLevels: { ...preset.skillLevels }, weapon: { ...preset.weapon }, finalStats: { ...preset.finalStats, elementalDamageBonus: { ...preset.finalStats.elementalDamageBonus }, damageTypeBonus: { ...preset.finalStats.damageTypeBonus } }, createdAt: "fixture", updatedAt: "fixture" }; }
const aemeathActor = (actorId="slot-aemeath"): TeamActorInput => ({ actorId, resonator:aemeath, build:build(aemeathPreset,`build-${actorId}`) });
const verinaActor = (actorId="slot-verina"): TeamActorInput => ({ actorId, resonator:verina, build:build(verinaPreset,`build-${actorId}`), weapon:variation, sonata:rejuvenatingGlow, mainEcho:fallacyOfNoReturn, coordinatedResponses:[photosynthesisResponse] });
const chisaActor = (actorId="slot-chisa"): TeamActorInput => ({ actorId, resonator:chisa, build:build(chisaPreset,`build-${actorId}`), weapon:kumokiri, sonata:threadOfSeveredFate, mainEcho:threnodianLeviathan });

function markedTargets(verinaId:string, aId:string) { const setup=createTeamState({actors:[verinaActor(verinaId),aemeathActor(aId)],activeActorId:verinaId,targetIds:["target-a","target-b"],target});const definition=verinaPhotosynthesisEffect.statuses![0];applyTeamTargetStatus(setup,"target-a",definition,verinaId,0);return setup.targetsById; }

describe("Team Engine real catalog runtime binding",()=>{
 it("binds static catalog identity to actor identity without mutating or leaking catalog state",()=>{const before=JSON.stringify(verina);const first=createTeamState({actors:[verinaActor("instance-one")],activeActorId:"instance-one",target});first.actorsById["instance-one"].resources.concerto.current=100;first.cooldowns.test=5;const second=createTeamState({actors:[verinaActor("instance-two")],activeActorId:"instance-two",target});expect(first.actorsById["instance-one"].runtime.effects[0]?.sourceEntityId).toBe("verina");expect(first.actorsById["instance-one"].runtime.effects[0]?.ownerActorId).toBe("instance-one");expect(second.actorsById["instance-two"].resources.concerto.current).toBe(0);expect(second.cooldowns).toEqual({});expect(JSON.stringify(verina)).toBe(before);});
 it("resolves real actions and exact talent data and discovers Intro by talent semantics",()=>{const runtime=bindTeamActorRuntime(verinaActor("runtime-v"));const resolved=resolveTeamActorAction(runtime,verinaActor("runtime-v").build,"verina-botany-experiment");expect(resolved.status).toBe("supported");expect(resolved.status==="supported"&&resolved.action.level).toBe(10);expect(discoverTeamIntroActions(runtime).map(action=>action.id)).toEqual(["verina-intro"]);const unsupportedBuild={...verinaActor("runtime-v").build,skillLevels:{...verinaActor("runtime-v").build.skillLevels,resonanceSkill:2}};expect(resolveTeamActorAction(runtime,unsupportedBuild,"verina-botany-experiment")).toMatchObject({status:"unsupported",code:"missing-exact-talent-data"});});
 it("derives real catalog Intro/Outro ownership and structured runtime amplification",()=>{const outgoing={...verinaActor("outgoing-v"),initialResources:{concerto:100}};const result=simulateTeam({actors:[outgoing,aemeathActor("incoming-a")],activeActorId:"outgoing-v",target,steps:[{kind:"switch",toActorId:"incoming-a"},{kind:"action",actorId:"incoming-a",actionId:"aemeath-basic-1",durationOverrideSeconds:0}]});const outro=result.eventLog.find(event=>event.kind==="outro")!,intro=result.eventLog.find(event=>event.kind==="intro")!;expect(outro.ownerId).toBe("outgoing-v");expect(intro.ownerId).toBe("incoming-a");expect(intro.payload?.actionIds).toEqual(["intro-normal"]);expect(result.actorsById["outgoing-v"].resources.concerto.current).toBe(0);expect(result.activeEffects.find(effect=>effect.definition.id==="verina-outro-amplification")).toMatchObject({ownerId:"outgoing-v",affectedEntityIds:["outgoing-v","incoming-a"]});expect(result.damageEvents.at(-1)?.effectAudit.some(entry=>entry.contributions.some(contribution=>contribution.kind==="damage-amplification"))).toBe(true);});
 it("refreshes repeated real Verina Outro amplification instead of stacking",()=>{const state=createTeamState({actors:[verinaActor("v"),aemeathActor("a")],activeActorId:"a",target});activateTeamEffect(state,verinaOutroAmplificationEffect,"v");state.currentTimeSeconds=5;activateTeamEffect(state,verinaOutroAmplificationEffect,"v");expect(state.activeEffects.filter(effect=>effect.definition.id==="verina-outro-amplification")).toHaveLength(1);expect(state.activeEffects[0].endTimeSeconds).toBe(35);});
 it("runs the real off-field Photosynthesis response from explicit qualifying events with runtime ownership",()=>{const external=[0,.5,1].map((timestamp,index)=>({id:`external-${index}`,timestamp,kind:"damage-dealt" as const,ownerId:"slot-aemeath",actorId:"slot-aemeath",targetId:"target-a",actionId:"aemeath-basic-1",external:true}));const result=simulateTeam({actors:[verinaActor(),aemeathActor()],activeActorId:"slot-verina",targetIds:["target-a","target-b"],initialTargetsById:markedTargets("slot-verina","slot-aemeath"),externalEvents:external,target,steps:[{kind:"switch",toActorId:"slot-aemeath"},{kind:"action",actorId:"slot-aemeath",actionId:"aemeath-basic-1",targetId:"target-a",durationOverrideSeconds:0},{kind:"wait",seconds:1}]});const direct=result.damageEvents.filter(event=>event.actionId==="aemeath-basic-1"),responses=result.damageEvents.filter(event=>event.actionId==="verina-coordinated-attack");expect(direct).toHaveLength(1);expect(direct[0]).toMatchObject({damageOwnerId:"slot-aemeath",scalingOwnerId:"slot-aemeath"});expect(responses).toHaveLength(2);expect(responses.every(event=>event.triggeringActorId==="slot-aemeath"&&event.damageOwnerId==="slot-verina"&&event.scalingOwnerId==="slot-verina"&&event.scalingStats.attack===verinaPreset.finalStats.attack)).toBe(true);expect(result.healingEvents.filter(event=>event.sourceEntityId==="verina-coordinated-attack")).toHaveLength(2);expect(Object.values(result.targetsById["target-b"].statuses)).toHaveLength(0);});
 it("keeps real Chisa target state runtime-owned after switch and separates target DEF reduction from attacker DEF ignore",()=>{const negative=chisa.combat!.effects.find(effect=>effect.id==="chisa-negative-statuses")!.structuredEffect!,snare=negative.statuses!.find(status=>status.id==="unseen-snare")!,bane=negative.statuses!.find(status=>status.id==="havoc-bane")!;const setup=createTeamState({actors:[chisaActor(),aemeathActor()],activeActorId:"slot-chisa",targetIds:["target-a","target-b"],target});applyTeamTargetStatus(setup,"target-a",snare,"slot-chisa",0);applyTeamTargetStatus(setup,"target-a",bane,"slot-chisa",0,2);const thread=chisa.combat!.effects.find(effect=>effect.id==="thread-of-bane")!.structuredEffect!;activateTeamEffect(setup,thread,"slot-aemeath",{targetId:"target-a"});const result=simulateTeam({actors:[chisaActor(),aemeathActor()],activeActorId:"slot-chisa",targetIds:["target-a","target-b"],target,initialTargetsById:setup.targetsById,initialEffects:setup.activeEffects,steps:[{kind:"switch",toActorId:"slot-aemeath"},{kind:"action",actorId:"slot-aemeath",actionId:"aemeath-basic-1",targetId:"target-a",durationOverrideSeconds:0}]});expect(Object.values(result.targetsById["target-a"].statuses).every(status=>status.sourceOwnerId==="slot-chisa")).toBe(true);expect(Object.values(result.targetsById["target-b"].statuses)).toHaveLength(0);const audit=result.damageEvents.find(event=>event.actionId==="aemeath-basic-1")!.effectAudit.flatMap(entry=>entry.contributions.map(contribution=>contribution.kind));expect(audit).toContain("defense-reduction");expect(audit).toContain("defense-ignore");});
 it("does not apply real Chisa hit-trigger status without verified hit timing",()=>{const result=simulateTeam({actors:[chisaActor()],activeActorId:"slot-chisa",targetIds:["target-a"],target,steps:[{kind:"action",actorId:"slot-chisa",actionId:"chisa-eye-of-unraveling",targetId:"target-a",durationOverrideSeconds:0}]});expect(Object.values(result.targetsById["target-a"].statuses)).toHaveLength(0);expect(result.eventLog.some(event=>event.kind==="action-hit")).toBe(false);});
 it("atomically aborts real actions whose before-action cost cannot be paid",()=>{const verinaResult=simulateTeam({actors:[verinaActor()],activeActorId:"slot-verina",target,steps:[{kind:"action",actorId:"slot-verina",actionId:"verina-arboreal-flourish",durationOverrideSeconds:0}]});expect(verinaResult.diagnostics.some(item=>item.code==="action-resource-rejected")).toBe(true);expect(verinaResult.damageEvents).toHaveLength(0);expect(verinaResult.healingEvents).toHaveLength(0);expect(verinaResult.eventLog.some(event=>event.kind==="action-start")).toBe(false);const chisaResult=simulateTeam({actors:[chisaActor()],activeActorId:"slot-chisa",target,steps:[{kind:"action",actorId:"slot-chisa",actionId:"chisa-moment-of-nihility",durationOverrideSeconds:0}]});expect(chisaResult.diagnostics.some(item=>item.code==="action-resource-rejected")).toBe(true);expect(chisaResult.damageEvents).toHaveLength(0);});
 it("does not trigger a real coordinated response from a non-damaging or missing-hit action",()=>{const result=simulateTeam({actors:[verinaActor(),aemeathActor()],activeActorId:"slot-verina",targetIds:["target-a"],initialTargetsById:markedTargets("slot-verina","slot-aemeath"),target,steps:[{kind:"action",actorId:"slot-verina",actionId:"verina-basic-5",targetId:"target-a",durationOverrideSeconds:0}]});expect(result.damageEvents.filter(event=>event.actionId==="verina-coordinated-attack")).toHaveLength(0);expect(result.eventLog.filter(event=>event.kind==="action-hit")).toHaveLength(0);});
 it("is invariant to real input order and changed actor instance ids",()=>{const actorsA=[verinaActor("v"),aemeathActor("a"),chisaActor("c")],actorsB=[chisaActor("c"),verinaActor("v"),aemeathActor("a")];for(const actors of [actorsA,actorsB]){const state=createTeamState({actors,activeActorId:"a",target});expect(state.actorsById.v.resonatorId).toBe("verina");expect(state.actorsById.a.finalStats.attack).toBe(aemeathPreset.finalStats.attack);expect(state.actorsById.c.runtime.effects.every(effect=>effect.ownerActorId==="c")).toBe(true);}});
});
