import {describe,expect,it} from "vitest";
import type {CombatAction, FinalStats, Resonator, UserBuild} from "./models";
import type {EffectDefinition} from "./effect-models";
import {activateTeamEffect,createTeamState,resolveTeamRecipients,setTeamTargetStatus,simulateTeam,SWITCH_BACK_COOLDOWN_SECONDS} from "./team-engine";

const source={kind:"technical-fixture" as const,source:"team test"};
const stats=(attack:number):FinalStats=>({hp:1000,attack,defense:100,critRate:0,critDamage:150,energyRegen:100,healingBonus:0,tuneBreakBoost:0,elementalDamageBonus:{aero:0,glacio:0,electro:0,fusion:0,havoc:0,spectro:0},damageTypeBonus:{basicAttack:0,heavyAttack:0,resonanceSkill:0,resonanceLiberation:0,introSkill:0,echoSkill:0}});
const action=(id:string,duration:number|null=1):CombatAction=>({id,name:id,talent:"basicAttack",damageType:"basicAttack",level:1,multipliers:[{percent:100,hits:1}],castDurationSeconds:{value:duration,confidence:duration===null?"unknown":"technical-fixture"},recoverySeconds:{value:0,confidence:"technical-fixture"},hitTimingsSeconds:{value:[0],confidence:"technical-fixture"},source});
function actor(actorId:string,resonatorId:string,attack:number,concerto=0){const a=action(`${resonatorId}-hit`);const resonator:Resonator={id:resonatorId,name:resonatorId,element:"spectro",weaponType:"rectifier",rarity:5,skillNames:{basicAttack:"",resonanceSkill:"",forteCircuit:"",resonanceLiberation:"",introSkill:""},resonanceChain:[],combat:{level10Only:false,forms:[],modes:[],resources:[{id:`${resonatorId}-meter`,name:"Meter",cap:100,semantic:"concerto-energy",notes:[]}],actions:[a],effects:[],rotations:[],unknowns:[],source},source};const build:UserBuild={id:`build-${actorId}`,resonatorId,sourcePresetId:"fixture",characterLevel:90,sequence:0,skillLevels:{basicAttack:1,resonanceSkill:1,forteCircuit:1,resonanceLiberation:1,introSkill:1},weapon:{weaponId:"fixture",level:90,rank:1},finalStats:stats(attack),createdAt:"",updatedAt:""};return{actorId,resonator,build,initialResources:{[`${resonatorId}-meter`]:concerto}};}
const target={level:90,elementalResistance:{spectro:0},physicalResistance:0};
const effect=(targetScope:EffectDefinition["target"],endOnSwitchOut?:"affected-recipient"|"owner"):EffectDefinition=>({id:`effect-${targetScope}`,label:"fixture",source:{id:"fixture",type:"system",label:"fixture"},target:targetScope,activationPolicy:"manual-only",rules:[],lifecycle:{duration:{kind:"fixed",seconds:14},endOnSwitchOut}});

describe("universal team engine",()=>{
 it("initializes one to three actor instances, rejects duplicate ids, and is order independent",()=>{const x=actor("slot-x","res-x",100),y=actor("slot-y","res-y",300);expect(Object.keys(createTeamState({actors:[x,y],activeActorId:"slot-x",target} as never).actorsById)).toEqual(["slot-x","slot-y"]);expect(createTeamState({actors:[y,x],activeActorId:"slot-x",target} as never).actorsById["slot-x"].finalStats.attack).toBe(100);expect(createTeamState({actors:[x,x],activeActorId:"slot-x",target} as never).diagnostics[0].code).toBe("duplicate-actor-id");});
 it("allows only the active actor direct actions and requires unknown timing",()=>{const x=actor("x","rx",100),y=actor("y","ry",200);(y as typeof y & {actions:CombatAction[]}).actions=[action("unknown",null)];const r=simulateTeam({actors:[x,y],activeActorId:"x",target,steps:[{kind:"action",actorId:"y",actionId:"ry-hit"},{kind:"switch",toActorId:"y"},{kind:"action",actorId:"y",actionId:"unknown"}]});expect(r.diagnostics.map(d=>d.code)).toEqual(expect.arrayContaining(["inactive-actor-action","timing-required"]));expect(r.resolvedDurationSeconds).toBeUndefined();});
 it("switches without resets and isolates the exact per-actor return cooldown",()=>{const a=actor("a","ra",100),b=actor("b","rb",100),c=actor("c","rc",100);const r=simulateTeam({actors:[a,b,c],activeActorId:"a",target,steps:[{kind:"switch",toActorId:"b"},{kind:"switch",toActorId:"c"},{kind:"switch",toActorId:"a"},{kind:"wait",seconds:SWITCH_BACK_COOLDOWN_SECONDS},{kind:"switch",toActorId:"a"}]});expect(r.diagnostics.filter(d=>d.code==="switch-cooldown")).toHaveLength(1);expect(r.activeActorId).toBe("a");expect(r.currentTimeSeconds).toBe(1);expect(r.actorsById.a.resources["ra-meter"].current).toBe(0);});
 it("derives plain versus semantic full-Concerto Intro/Outro and consumes only outgoing resource",()=>{const plain=simulateTeam({actors:[actor("a","ra",100),actor("b","rb",100)],activeActorId:"a",target,steps:[{kind:"switch",toActorId:"b"}]});expect(plain.eventLog.some(e=>e.kind==="intro"||e.kind==="outro")).toBe(false);const ready=simulateTeam({actors:[actor("a","ra",100,100),actor("b","rb",100,50)],activeActorId:"a",target,steps:[{kind:"switch",toActorId:"b"}]});expect(ready.eventLog.map(e=>e.kind)).toEqual(["switch-out","outro","switch-in","intro"]);expect(ready.actorsById.a.resources["ra-meter"].current).toBe(0);expect(ready.actorsById.b.resources["rb-meter"].current).toBe(50);});
 it("resolves all generic scopes and expires only the affected switched-out recipient",()=>{const actors=[actor("a","ra",1),actor("b","rb",1),actor("c","rc",1)];const state=createTeamState({actors,activeActorId:"a",targetIds:["enemy"],target});expect(resolveTeamRecipients("team","a",state)).toEqual(["a","b","c"]);expect(resolveTeamRecipients("other-team-members","a",state)).toEqual(["b","c"]);expect(resolveTeamRecipients("incoming-resonator","a",state,{incomingActorId:"b"})).toEqual(["b"]);expect(resolveTeamRecipients("active-resonator","b",state)).toEqual(["a"]);expect(resolveTeamRecipients("enemy","a",state)).toEqual(["enemy"]);activateTeamEffect(state,effect("incoming-resonator","affected-recipient"),"a",{incomingActorId:"b"});const unrelated=simulateTeam({actors,activeActorId:"a",target,initialEffects:state.activeEffects,steps:[{kind:"switch",toActorId:"c"}]});expect(unrelated.activeEffects).toHaveLength(1);const recipientLeaves=simulateTeam({actors,activeActorId:"b",target,initialEffects:state.activeEffects,steps:[{kind:"switch",toActorId:"c"}]});expect(recipientLeaves.activeEffects).toHaveLength(0);});
 it("uses scalingOwner stats and independently attributes an off-field queued response",()=>{const a=actor("attacker","ra",100),owner=actor("owner","rb",500);(owner as typeof owner & {actions:CombatAction[]}).actions=[action("response")];const r=simulateTeam({actors:[a,owner],activeActorId:"attacker",targetIds:["A","B"],target,scheduledActions:[{actorId:"owner",actionId:"response",targetId:"A",damageOwnerId:"owner",scalingOwnerId:"owner",triggeringActorId:"attacker",delaySeconds:.5}],steps:[{kind:"switch",toActorId:"owner"},{kind:"wait",seconds:.5}]});const response=r.damageEvents.find(e=>e.actionId==="response")!;expect(response.damageOwnerId).toBe("owner");expect(response.scalingOwnerId).toBe("owner");expect(response.triggeringActorId).toBe("attacker");expect(response.scalingStats.attack).toBe(500);expect(response.timestamp).toBe(.5);});
 it("keeps target status and target-local ICD state isolated across switch",()=>{const state=createTeamState({actors:[actor("a","ra",1),actor("b","rb",1)],activeActorId:"a",targetIds:["A","B"],target});const status={stacks:1,sourceOwnerId:"a",definition:{id:"mark",label:"mark",maxStacks:1}};setTeamTargetStatus(state,"A","mark",status);state.cooldowns["target:A:response"]=1;expect(state.targetsById.A.statuses.mark.sourceOwnerId).toBe("a");expect(state.targetsById.B.statuses.mark).toBeUndefined();expect(state.cooldowns["target:B:response"]).toBeUndefined();});
 it("never falls back to active stats for an unknown scaling owner",()=>{const r=simulateTeam({actors:[actor("a","ra",1)],activeActorId:"a",target,scheduledActions:[{actorId:"a",actionId:"ra-hit",targetId:"target",damageOwnerId:"a",scalingOwnerId:"missing"}],steps:[{kind:"wait",seconds:0}]});expect(r.diagnostics.some(d=>d.code==="missing-scaling-owner")).toBe(true);expect(r.damageEvents).toHaveLength(0);});
 it("never falls back to active ownership for a missing damage owner",()=>{const r=simulateTeam({actors:[actor("a","ra",1)],activeActorId:"a",target,scheduledActions:[{actorId:"a",actionId:"ra-hit",targetId:"target",scalingOwnerId:"a"}],steps:[{kind:"wait",seconds:0}]});expect(r.diagnostics.some(d=>d.code==="missing-damage-owner")).toBe(true);expect(r.damageEvents).toHaveLength(0);});
 it("discovers structured Outro listeners without parsing prose",()=>{const outroEffect:EffectDefinition={...effect("incoming-resonator"),id:"structured-outro",triggers:[{id:"on-outro",event:"outro",operations:[{kind:"activate-effect",effectId:"structured-outro"}]}]};const sourceActor=actor("source","rs",1,100);(sourceActor as typeof sourceActor&{effects:EffectDefinition[]}).effects=[outroEffect];const state=createTeamState({actors:[sourceActor,actor("incoming","ri",1)],activeActorId:"source",target});expect(state.actorsById.source.runtime.outroEffects.map(bound=>bound.definition.id)).toEqual(["structured-outro"]);});
});
