import type { MainEcho, Resonator, Sonata, UserBuild, Weapon } from "./models";
import type { TeamActorInput, TeamRotationStep } from "./team-engine";
import { resolveActionTalentLevel } from "./talent-engine";

export const TEAM_ROTATION_STORAGE_VERSION = 1;
export interface TeamRotationDraft {version:1;selectedBuildIds:readonly string[];actorIds:readonly string[];startingActorId:string;steps:readonly TeamRotationStep[];initialResourcesByActorId?:Readonly<Record<string,Readonly<Record<string,number>>>>;}
export interface RotationActionOption {id:string;name:string;timing:"verified"|"missing";talentStatus:"exact"|"missing-exact-talent-data";}

export function actorIdForBuild(buildId:string):string{return `team-build-${buildId}`;}
export function deriveRotationActionOptions(resonator:Resonator,build:UserBuild):readonly RotationActionOption[]{return (resonator.combat?.actions??[]).filter(action=>action.talent!=="introSkill").map(action=>{const level=build.skillLevels[action.talent as keyof UserBuild["skillLevels"]];return{id:action.id,name:action.name,timing:action.castDurationSeconds.value===null?"missing":"verified",talentStatus:resolveActionTalentLevel(action,level).status==="supported"?"exact":"missing-exact-talent-data"};});}
export function walkRotationActiveActors(startingActorId:string,steps:readonly TeamRotationStep[]):readonly string[]{let active=startingActorId;return steps.map(step=>{const expected=active;if(step.kind==="switch")active=step.toActorId;return expected;});}
export function buildTeamActorInputs(builds:readonly UserBuild[],catalog:{resonators:readonly Resonator[];weapons:readonly Weapon[];sonatas:readonly Sonata[];mainEchoes:readonly MainEcho[]},initialResourcesByActorId:Readonly<Record<string,Readonly<Record<string,number>>>>={},actorIdsByBuildId:Readonly<Record<string,string>>={}):{actors:TeamActorInput[];diagnostics:string[]}{const diagnostics:string[]=[],actors:TeamActorInput[]=[];for(const build of builds){const resonator=catalog.resonators.find(item=>item.id===build.resonatorId);if(!resonator){diagnostics.push(`stale-resonator:${build.resonatorId}`);continue;}const weapon=catalog.weapons.find(item=>item.id===build.weapon.weaponId),sonata=catalog.sonatas.find(item=>item.id===build.sonataId),mainEcho=catalog.mainEchoes.find(item=>item.id===build.mainEchoId);if(!weapon)diagnostics.push(`stale-weapon:${build.weapon.weaponId}`);if(build.sonataId&&!sonata)diagnostics.push(`stale-sonata:${build.sonataId}`);if(build.mainEchoId&&!mainEcho)diagnostics.push(`stale-echo:${build.mainEchoId}`);const actorId=actorIdsByBuildId[build.id]??actorIdForBuild(build.id),initialResources=Object.fromEntries((resonator.combat?.resources??[]).map(resource=>[resource.id,Math.min(resource.cap,Math.max(0,initialResourcesByActorId[actorId]?.[resource.id]??0))]));actors.push({actorId,resonator,build,weapon,sonata,mainEcho,initialResources});}return{actors,diagnostics};}
export function parseTeamRotationDraft(value:string|null):TeamRotationDraft|undefined{if(!value)return;try{const parsed=JSON.parse(value) as Partial<TeamRotationDraft>;if(parsed.version!==1||!Array.isArray(parsed.selectedBuildIds)||!Array.isArray(parsed.actorIds)||typeof parsed.startingActorId!=="string"||!Array.isArray(parsed.steps))return;return parsed as TeamRotationDraft;}catch{return;}}
