import { describe, expect, it } from "vitest";
import { aemeath, aemeathPreset } from "@/data/aemeath";
import { chisa, chisaPreset, kumokiri, threadOfSeveredFate, threnodianLeviathan } from "@/data/chisa";
import { fallacyOfNoReturn, photosynthesisResponse, rejuvenatingGlow, variation, verina, verinaPhotosynthesisEffect, verinaPreset } from "@/data/verina";
import type { RecommendedBuildPreset, UserBuild } from "./models";
import { activateTeamEffect, applyTeamTargetStatus, createTeamState, simulateTeam, type TeamActorInput } from "./team-engine";
import { bindTeamActorRuntime, discoverTeamIntroActions, resolveTeamActorAction } from "./team-runtime-binding";

const target = { level: 90, elementalResistance: { fusion: 0, havoc: 0, spectro: 0 }, physicalResistance: 0 };
function build(preset: RecommendedBuildPreset, id: string): UserBuild { return { ...preset, id, sourcePresetId: preset.id, skillLevels: { ...preset.skillLevels }, weapon: { ...preset.weapon }, finalStats: { ...preset.finalStats, elementalDamageBonus: { ...preset.finalStats.elementalDamageBonus }, damageTypeBonus: { ...preset.finalStats.damageTypeBonus } }, createdAt: "fixture", updatedAt: "fixture" }; }
const aemeathActor = (actorId="slot-aemeath"): TeamActorInput => ({ actorId, resonator:aemeath, build:build(aemeathPreset,`build-${actorId}`) });
const verinaActor = (actorId="slot-verina"): TeamActorInput => ({ actorId, resonator:verina, build:build(verinaPreset,`build-${actorId}`), weapon:variation, sonata:rejuvenatingGlow, mainEcho:fallacyOfNoReturn, coordinatedResponses:[photosynthesisResponse] });
const chisaActor = (actorId="slot-chisa"): TeamActorInput => ({ actorId, resonator:chisa, build:build(chisaPreset,`build-${actorId}`), weapon:kumokiri, sonata:threadOfSeveredFate, mainEcho:threnodianLeviathan });

function markedTargets(verinaId:string, aId:string) { const setup=createTeamState({actors:[verinaActor(verinaId),aemeathActor(aId)],activeActorId:verinaId,targetIds:["target-a","target-b"],target});const definition=verinaPhotosynthesisEffect.statuses![0];applyTeamTargetStatus(setup,"target-a",definition,verinaId,0);return setup.targetsById; }

describe("Team Engine real catalog runtime binding",()=>{
 it("binds static catalog identity to actor identity without mutating or leaking catalog state",()=>{const before=JSON.stringify(verina);const first=createTeamState({actors:[verinaActor("instance-one")],activeActorId:"instance-one",target});first.actorsById["instance-one"].resources.concerto.current=100;first.cooldowns.test=5;const second=createTeamState({actors:[verinaActor("instance-two")],activeActorId:"instance-two",target});expect(first.actorsById["instance-one"].runtime.effects[0]?.sourceEntityId).toBe("verina");expect(first.actorsById["instance-one"].runtime.effects[0]?.ownerActorId).toBe("instance-one");expect(second.actorsById["instance-two"].resources.concerto.current).toBe(0);expect(second.cooldowns).toEqual({});expect(JSON.stringify(verina)).toBe(before);});
 it("resolves real actions and exact talent data and discovers Intro by talent semantics",()=>{const runtime=bindTeamActorRuntime(verinaActor("runtime-v"));const resolved=resolveTeamActorAction(runtime,verinaActor("runtime-v").build,"verina-botany-experiment");expect(resolved.status).toBe("supported");expect(resolved.status==="supported"&&resolved.action.level).toBe(10);expect(discoverTeamIntroActions(runtime).map(action=>action.id)).toEqual(["verina-intro"]);const unsupportedBuild={...verinaActor("runtime-v").build,skillLevels:{...verinaActor("runtime-v").build.skillLevels,resonanceSkill:2}};expect(resolveTeamActorAction(runtime,unsupportedBuild,"verina-botany-experiment")).toMatchObject({status:"unsupported",code:"missing-exact-talent-data"});});
 it("derives real catalog Intro/Outro ownership and structured runtime amplification",()=>{const outgoing={...verinaActor("outgoing-v"),initialResources:{concerto:100}};const result=simulateTeam({actors:[outgoing,aemeathActor("incoming-a")],activeActorId:"outgoing-v",target,steps:[{kind:"switch",toActorId:"incoming-a"},{kind:"action",actorId:"incoming-a",actionId:"aemeath-basic-1",durationOverrideSeconds:0}]});const outro=result.eventLog.find(event=>event.kind==="outro")!,intro=result.eventLog.find(event=>event.kind==="intro")!;expect(outro.ownerId).toBe("outgoing-v");expect(intro.ownerId).toBe("incoming-a");expect(intro.payload?.actionIds).toEqual(["intro-normal","intro-mech"]);expect(result.actorsById["outgoing-v"].resources.concerto.current).toBe(0);expect(result.activeEffects.find(effect=>effect.definition.id==="verina-outro-amplification")).toMatchObject({ownerId:"outgoing-v",affectedEntityIds:["outgoing-v","incoming-a"]});expect(result.damageEvents.at(-1)?.effectAudit.some(entry=>entry.contributions.some(contribution=>contribution.kind==="damage-amplification"))).toBe(true);});
 it("runs the real off-field Photosynthesis response with runtime ownership, healing, ICD, and target isolation",()=>{const result=simulateTeam({actors:[verinaActor(),aemeathActor()],activeActorId:"slot-verina",targetIds:["target-a","target-b"],initialTargetsById:markedTargets("slot-verina","slot-aemeath"),target,steps:[{kind:"switch",toActorId:"slot-aemeath"},{kind:"action",actorId:"slot-aemeath",actionId:"aemeath-basic-1",targetId:"target-a",durationOverrideSeconds:0},{kind:"wait",seconds:.5},{kind:"action",actorId:"slot-aemeath",actionId:"aemeath-basic-1",targetId:"target-a",durationOverrideSeconds:0},{kind:"wait",seconds:.5},{kind:"action",actorId:"slot-aemeath",actionId:"aemeath-basic-1",targetId:"target-a",durationOverrideSeconds:0}]});const direct=result.damageEvents.filter(event=>event.actionId==="aemeath-basic-1"),responses=result.damageEvents.filter(event=>event.actionId==="verina-coordinated-attack");expect(direct).toHaveLength(3);expect(direct.every(event=>event.damageOwnerId==="slot-aemeath"&&event.scalingOwnerId==="slot-aemeath")).toBe(true);expect(responses).toHaveLength(2);expect(responses.every(event=>event.triggeringActorId==="slot-aemeath"&&event.damageOwnerId==="slot-verina"&&event.scalingOwnerId==="slot-verina"&&event.scalingStats.attack===verinaPreset.finalStats.attack)).toBe(true);expect(result.healingEvents.filter(event=>event.sourceEntityId==="verina-coordinated-attack")).toHaveLength(2);expect(result.healingEvents.find(event=>event.sourceEntityId==="verina-coordinated-attack")?.scalingOwnerId).toBe("slot-verina");expect(Object.values(result.targetsById["target-b"].statuses)).toHaveLength(0);expect(result.activeActorId).toBe("slot-aemeath");});
 it("keeps real Chisa target state runtime-owned after switch and separates target DEF reduction from attacker DEF ignore",()=>{const thread=chisa.combat!.effects.find(effect=>effect.id==="thread-of-bane")!.structuredEffect!;const threadState=createTeamState({actors:[chisaActor(),aemeathActor()],activeActorId:"slot-chisa",targetIds:["target-a","target-b"],target});activateTeamEffect(threadState,thread,"slot-aemeath",{targetId:"target-a"});const result=simulateTeam({actors:[chisaActor(),aemeathActor()],activeActorId:"slot-chisa",targetIds:["target-a","target-b"],target,initialEffects:threadState.activeEffects,steps:[{kind:"action",actorId:"slot-chisa",actionId:"chisa-eye-of-unraveling",targetId:"target-a",durationOverrideSeconds:0},{kind:"switch",toActorId:"slot-aemeath"},{kind:"action",actorId:"slot-aemeath",actionId:"aemeath-basic-1",targetId:"target-a",durationOverrideSeconds:0}]});expect(Object.values(result.targetsById["target-a"].statuses).every(status=>status.sourceOwnerId==="slot-chisa")).toBe(true);expect(Object.values(result.targetsById["target-b"].statuses)).toHaveLength(0);const audit=result.damageEvents.find(event=>event.actionId==="aemeath-basic-1")!.effectAudit.flatMap(entry=>entry.contributions.map(contribution=>contribution.kind));expect(audit).toContain("defense-reduction");expect(audit).toContain("defense-ignore");});
 it("is invariant to real input order and changed actor instance ids",()=>{const actorsA=[verinaActor("v"),aemeathActor("a"),chisaActor("c")],actorsB=[chisaActor("c"),verinaActor("v"),aemeathActor("a")];for(const actors of [actorsA,actorsB]){const state=createTeamState({actors,activeActorId:"a",target});expect(state.actorsById.v.resonatorId).toBe("verina");expect(state.actorsById.a.finalStats.attack).toBe(aemeathPreset.finalStats.attack);expect(state.actorsById.c.runtime.effects.every(effect=>effect.ownerActorId==="c")).toBe(true);}});
});
