"use client";
import Link from "next/link";
import {useEffect,useState,useSyncExternalStore} from "react";
import {mainEchoes,resonators,sonatas,weapons} from "@/data/catalog";
import {emptyCharacterBox} from "@/domain/character-box";
import {buildTeamActorInputs,deriveRotationActionOptions,TEAM_ROTATION_STORAGE_VERSION,walkRotationActiveActors} from "@/domain/team-rotation-builder";
import {simulateTeam,type TeamRotationStep,type TeamSimulationResult} from "@/domain/team-engine";
import {getBrowserCharacterBoxSnapshot,subscribeToBrowserCharacterBox} from "@/storage/character-box-storage";
import {loadTeamRotationDraft,saveTeamRotationDraft} from "@/storage/team-rotation-storage";

const target={level:90,elementalResistance:{aero:0,glacio:0,electro:0,fusion:0,havoc:0,spectro:0},physicalResistance:0};
export function TeamRotationLab(){const box=useSyncExternalStore(subscribeToBrowserCharacterBox,getBrowserCharacterBoxSnapshot,emptyCharacterBox);const[buildIds,setBuildIds]=useState<string[]>([]),[starting,setStarting]=useState("team-slot-1"),[steps,setSteps]=useState<TeamRotationStep[]>([]),[result,setResult]=useState<TeamSimulationResult>(),[storageReady,setStorageReady]=useState(false);useEffect(()=>{const timer=window.setTimeout(()=>{const saved=loadTeamRotationDraft();if(saved){setBuildIds([...saved.selectedBuildIds]);setStarting(saved.startingActorId);setSteps([...saved.steps]);}setStorageReady(true);},0);return()=>window.clearTimeout(timer);},[]);useEffect(()=>{if(storageReady)saveTeamRotationDraft({version:TEAM_ROTATION_STORAGE_VERSION,selectedBuildIds:buildIds,actorIds:buildIds.map((_,i)=>`team-slot-${i+1}`),startingActorId:starting,steps});},[buildIds,starting,steps,storageReady]);
 const staleBuildDiagnostics=buildIds.filter(id=>!box.builds.some(build=>build.id===id)).map(id=>`stale-build:${id}`),selected=buildIds.map(id=>box.builds.find(build=>build.id===id)).filter((build):build is NonNullable<typeof build>=>Boolean(build)),prepared=buildTeamActorInputs(selected,{resonators,weapons,sonatas,mainEchoes}),expected=walkRotationActiveActors(starting,steps),authoredActive=steps.reduce((active,step)=>step.kind==="switch"?step.toActorId:active,starting),activeActor=prepared.actors.find(actor=>actor.actorId===authoredActive),actionOptions=activeActor?deriveRotationActionOptions(activeActor.resonator,activeActor.build):[];
 function toggleBuild(id:string){setBuildIds(ids=>ids.includes(id)?ids.filter(item=>item!==id):ids.length<3?[...ids,id]:ids);setResult(undefined);}function addAction(id:string){if(!activeActor)return;setSteps(items=>[...items,{kind:"action",actorId:activeActor.actorId,actionId:id}]);}function move(index:number,delta:number){setSteps(items=>{const next=[...items],to=index+delta;if(to<0||to>=next.length)return items;[next[index],next[to]]=[next[to],next[index]];return next;});}
 function run(){if(!prepared.actors.length)return;setResult(simulateTeam({actors:prepared.actors,activeActorId:starting,target,steps}));}
 return <main className="min-h-screen px-4 py-8 sm:px-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--line)] pb-6"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-[var(--accent)]">Team Lab · V0.1</p><h1 className="mt-2 text-3xl font-semibold">Team Composition + Rotation Validation</h1><p className="mt-2 text-sm text-[var(--muted)]">Sequential validation only. No final Team DPS or cycle claim.</p></div><Link className="rounded-xl border border-[var(--line)] px-4 py-2 text-sm" href="/">Character Box</Link></header>
 <section className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><h2 className="text-lg font-semibold">1. Saved builds (1–3 unique)</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{box.builds.map(build=>{const resonator=resonators.find(item=>item.id===build.resonatorId);const selectedIndex=buildIds.indexOf(build.id);return <button key={build.id} onClick={()=>toggleBuild(build.id)} className={`rounded-xl border p-4 text-left ${selectedIndex>=0?"border-[var(--accent)] bg-white/5":"border-[var(--line)]"}`}><b>{resonator?.name??build.resonatorId}</b><span className="mt-1 block text-xs text-[var(--muted)]">{selectedIndex>=0?`team-slot-${selectedIndex+1}`:"Not selected"}</span></button>})}{box.builds.length===0&&<p className="text-sm text-[var(--muted)]">Create builds in Character Box first.</p>}</div><label className="mt-4 block text-sm">Starting actor <select className="ml-2 rounded-lg bg-black/30 p-2" value={starting} onChange={e=>setStarting(e.target.value)}>{prepared.actors.map(actor=><option key={actor.actorId} value={actor.actorId}>{actor.actorId} · {actor.resonator.name}</option>)}</select></label></section>
 <section className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><h2 className="text-lg font-semibold">2. Author rotation</h2><p className="mt-1 text-xs text-[var(--muted)]">Manual duration assigns sequential timeline time only; it is not hit, cancel, or frame timing.</p><div className="mt-4 flex flex-wrap gap-2"><select id="team-action" className="rounded-lg bg-black/30 p-2 text-sm">{actionOptions.map(option=><option key={option.id} value={option.id}>{option.name} · {option.timing==="verified"?"Verified":"Missing"} · {option.talentStatus}</option>)}</select><button className="rounded-lg bg-[var(--accent)] px-3 py-2 text-sm text-black" onClick={()=>{const el=document.getElementById("team-action") as HTMLSelectElement|null;if(el?.value)addAction(el.value)}}>+ Action</button><select id="team-switch" className="rounded-lg bg-black/30 p-2 text-sm">{prepared.actors.filter(actor=>actor.actorId!==authoredActive).map(actor=><option key={actor.actorId} value={actor.actorId}>{actor.actorId}</option>)}</select><button className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm" onClick={()=>{const el=document.getElementById("team-switch") as HTMLSelectElement|null;if(el?.value)setSteps(items=>[...items,{kind:"switch",toActorId:el.value}])}}>+ Switch</button><button className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm" onClick={()=>setSteps(items=>[...items,{kind:"wait",seconds:1}])}>+ Wait</button></div><ol className="mt-4 space-y-2">{steps.map((step,index)=><li key={index} className="flex flex-wrap items-center gap-3 rounded-xl border border-[var(--line)] p-3 text-sm"><span className="w-7 text-[var(--muted)]">{index+1}</span><b className="uppercase">{step.kind}</b><span>{step.kind==="action"?`${step.actorId} · ${step.actionId}`:step.kind==="switch"?`→ ${step.toActorId}`:`${step.seconds}s`}</span><span className="text-xs text-[var(--muted)]">expected active: {expected[index]}</span>{step.kind==="action"&&<input aria-label="Manual duration" className="w-28 rounded bg-black/30 p-1" type="number" min="0" step="0.1" placeholder="Manual sec" value={step.durationOverrideSeconds??""} onChange={e=>setSteps(items=>items.map((item,i)=>i===index&&item.kind==="action"?{...item,durationOverrideSeconds:e.target.value===""?undefined:Number(e.target.value)}:item))}/>}<span className="ml-auto flex gap-1"><button onClick={()=>move(index,-1)}>↑</button><button onClick={()=>move(index,1)}>↓</button><button onClick={()=>setSteps(items=>items.filter((_,i)=>i!==index))}>Delete</button></span></li>)}</ol><button onClick={run} disabled={!prepared.actors.length} className="mt-5 rounded-xl bg-[var(--accent)] px-5 py-3 font-bold text-black disabled:opacity-40">Run Rotation</button></section>
 {result&&<Result result={result} preDiagnostics={[...staleBuildDiagnostics,...prepared.diagnostics]}/>}</div></main>}
function Result({result,preDiagnostics}:{result:TeamSimulationResult;preDiagnostics:readonly string[]}){const invalid=preDiagnostics.length>0||result.diagnostics.some(item=>["unknown-team-actor","unknown-action","inactive-actor-action","invalid-switch-target","action-resource-rejected"].includes(item.code)),status=invalid?"Invalid":result.partial?"Partial":"Complete";return <section className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-5"><div className="flex justify-between"><h2 className="text-lg font-semibold">3. Result · {status}</h2><b>{result.currentTimeSeconds.toFixed(2)}s · active {result.activeActorId}</b></div><p className="mt-4 text-2xl font-semibold">{result.totalResolvedDamage.expected.toFixed(2)} <span className="text-xs text-amber-300">TOTAL RESOLVED DAMAGE — NOT FINAL TEAM DPS</span></p><div className="mt-5 grid gap-4 lg:grid-cols-2"><Report title="Damage by actor" value={Object.entries(result.damageByActorId).map(([id,v])=>`${id}: ${v.expected.toFixed(2)}`)}/><Report title="Resources" value={Object.values(result.actorsById).flatMap(actor=>Object.entries(actor.resources).map(([id,v])=>`${actor.actorId} · ${id}: ${v.current}/${v.max}`))}/><Report title="Target statuses" value={Object.entries(result.targetsById).flatMap(([target,state])=>Object.values(state.statuses).map(status=>`${target} · ${status.definition.label} · owner ${status.sourceOwnerId}`))}/><Report title="Diagnostics" value={[...preDiagnostics,...result.diagnostics.map(item=>`${item.code}: ${item.message}`)]}/></div><Report title="Chronological events / ownership" value={result.eventLog.map(event=>`${event.timestamp.toFixed(2)} · ${event.kind} · owner ${event.ownerId}${event.triggeringActorId?` · trigger ${event.triggeringActorId}`:""}`)}/></section>}
function Report({title,value}:{title:string;value:readonly string[]}){return <div className="mt-4 rounded-xl bg-black/20 p-4"><h3 className="font-semibold">{title}</h3><ul className="mt-2 space-y-1 text-xs text-[var(--muted)]">{value.length?value.map((line,i)=><li key={`${line}-${i}`}>{line}</li>):<li>None</li>}</ul></div>}
