"use client";

import Link from "next/link";
import Image from "next/image";
import { useMemo, useState, useSyncExternalStore } from "react";
import { emptyCharacterBox } from "@/domain/character-box";
import { damageTypes, elements, type FinalStats } from "@/domain/models";
import { DEFAULT_LAB_TARGET, calculateActionLab, compareObservedDamage, diagnosticsByFamily, isStandardDamage, resolvePersonalLoadout, simulateRotationLab, type LabTarget } from "@/domain/personal-dps-lab";
import type { StandardDamageResult } from "@/domain/damage-engine";
import type { PersonalCombatResult } from "@/domain/personal-combat-simulation";
import { getBrowserCharacterBoxSnapshot, subscribeToBrowserCharacterBox } from "@/storage/character-box-storage";

const serverBox = emptyCharacterBox();
const number = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value);
const cloneStats = (stats: FinalStats): FinalStats => structuredClone(stats);

export function PersonalDpsLab() {
  const box = useSyncExternalStore(subscribeToBrowserCharacterBox, getBrowserCharacterBoxSnapshot, () => serverBox);
  const [buildId, setBuildId] = useState<string>("");
  const build = box.builds.find((item) => item.id === buildId) ?? box.builds[0];
  const [sandbox, setSandbox] = useState<FinalStats | null>(null);
  const stats = sandbox ?? build?.finalStats;
  const loadout = useMemo(() => build ? resolvePersonalLoadout(build) : undefined, [build]);
  const [target, setTarget] = useState<LabTarget>(DEFAULT_LAB_TARGET);
  const [mode, setMode] = useState<"action" | "rotation">("action");
  const [actionId, setActionId] = useState("");
  const [manual, setManual] = useState<string[]>([]);
  const [resonanceMode, setResonanceMode] = useState("tune-rupture");
  const [observed, setObserved] = useState("");
  const selectedActionId = loadout?.actions.some((item) => item.id === actionId) ? actionId : loadout?.actions[0]?.id ?? "";
  const actionResult = useMemo(() => loadout && stats ? calculateActionLab({ loadout, actionId: selectedActionId, stats, target, manualEffectIds: manual, resonanceMode }) : undefined, [loadout, stats, selectedActionId, target, manual, resonanceMode]);
  const rotation = useMemo(() => mode === "rotation" && loadout && stats ? simulateRotationLab(loadout, stats, target, resonanceMode) : undefined, [mode, loadout, stats, target, resonanceMode]);
  const calculated = actionResult?.damage.status === "supported" ? actionResult.damage.total.expected : undefined;
  const delta = calculated !== undefined && observed !== "" ? compareObservedDamage(calculated, Number(observed)) : undefined;

  const editStat = (key: keyof Pick<FinalStats, "attack" | "hp" | "defense" | "critRate" | "critDamage" | "energyRegen" | "tuneBreakBoost">, value: number) => setSandbox({ ...cloneStats(stats!), [key]: value });
  const copySnapshot = async () => {
    if (!loadout || !stats) return;
    const snapshot = { resonator: loadout.resonator?.name, build: { level: build?.characterLevel, stats }, weapon: loadout.weapon?.name, weaponRank: build?.weapon.rank, sequence: build?.sequence, sonata: loadout.sonata?.name, mainEcho: loadout.mainEcho?.name, action: actionResult?.action.id, target, mode: resonanceMode, manualEffectOverrides: manual, calculatedResult: actionResult?.damage, observed: observed || undefined, delta, diagnostics: actionResult?.diagnostics, status: actionResult?.partial ? "PARTIAL" : "COMPLETE" };
    await navigator.clipboard.writeText(JSON.stringify(snapshot));
  };

  if (!box.builds.length) return <main className="lab-shell"><nav><Link href="/">← Character Box</Link></nav><section className="lab-empty"><h1>Personal DPS Lab</h1><p>No saved build. Add a Resonator in Character Box first.</p></section></main>;
  return <main className="lab-shell">
    <header className="lab-header"><div><p className="eyebrow">PERSONAL COMBAT · NO TEAM BUFFS</p><h1>Personal DPS Lab</h1><p>Inspect one action or the honest partial result of a data-owned rotation.</p></div><Link className="lab-link" href="/">← Character Box</Link></header>
    <div className="lab-tabs"><button className={mode === "action" ? "active" : ""} onClick={() => setMode("action")}>Action Lab</button><button className={mode === "rotation" ? "active" : ""} onClick={() => setMode("rotation")}>Rotation Lab</button></div>
    <div className="lab-grid">
      <aside className="lab-column">
        <Panel title="Build sandbox"><label>Saved build<select value={build?.id} onChange={(e) => { setBuildId(e.target.value); setSandbox(null); setManual([]); }} >{box.builds.map((item) => <option key={item.id} value={item.id}>{item.resonatorId} · Lv{item.characterLevel}</option>)}</select></label>
          {loadout?.resonator && <div className="build-summary">{loadout.resonator.portrait && <Image src={loadout.resonator.portrait.src} alt={loadout.resonator.portrait.alt} width={72} height={72}/>}<div><strong>{loadout.resonator.name}</strong><small>Lv{build?.characterLevel} · S{build?.sequence}</small><small>{loadout.weapon?.name} Lv{build?.weapon.level} R{build?.weapon.rank}</small><small>{loadout.sonata?.name} · {loadout.mainEcho?.name}</small></div></div>}
          <div className="stat-grid">{(["attack","hp","defense","critRate","critDamage","energyRegen","tuneBreakBoost"] as const).map((key) => <label key={key}>{key}<input type="number" value={stats?.[key] ?? 0} onChange={(e) => editStat(key, Number(e.target.value))}/></label>)}</div>
          <details><summary>Element & damage bonuses</summary><div className="stat-grid">{elements.map((key) => <label key={key}>{key}<input type="number" value={stats?.elementalDamageBonus[key]} onChange={(e) => setSandbox({ ...cloneStats(stats!), elementalDamageBonus: { ...stats!.elementalDamageBonus, [key]: Number(e.target.value) } })}/></label>)}{damageTypes.map((key) => <label key={key}>{key}<input type="number" value={stats?.damageTypeBonus[key]} onChange={(e) => setSandbox({ ...cloneStats(stats!), damageTypeBonus: { ...stats!.damageTypeBonus, [key]: Number(e.target.value) } })}/></label>)}</div></details>
          <button onClick={() => setSandbox(null)}>Reset from build</button>
        </Panel>
        <Panel title="Target"><p className="hint">Technical reset: Lv90, 10% elemental/Physical RES, Tune 4C. Not an official target.</p><div className="stat-grid"><label>Enemy level<input type="number" value={target.level} onChange={(e) => setTarget({ ...target, level: Number(e.target.value) })}/></label><label>Physical RES<input type="number" step="0.01" value={target.physicalResistance} onChange={(e) => setTarget({ ...target, physicalResistance: Number(e.target.value) })}/></label><label>Fusion RES<input type="number" step="0.01" value={target.elementalResistance.fusion ?? 0} onChange={(e) => setTarget({ ...target, elementalResistance: { ...target.elementalResistance, fusion: Number(e.target.value) } })}/></label><label>Havoc RES<input type="number" step="0.01" value={target.elementalResistance.havoc ?? 0} onChange={(e) => setTarget({ ...target, elementalResistance: { ...target.elementalResistance, havoc: Number(e.target.value) } })}/></label><label>Tune class<select value={target.tuneEnemyClass} onChange={(e) => setTarget({ ...target, tuneEnemyClass: e.target.value as LabTarget["tuneEnemyClass"] })}><option>1C</option><option>3C</option><option>4C</option></select></label></div><button onClick={() => setTarget(DEFAULT_LAB_TARGET)}>Reset target</button></Panel>
      </aside>
      <section className="lab-column lab-main">
        {mode === "action" ? <>
          <Panel title="Action"><label>Resonance mode<select value={resonanceMode} onChange={(e) => setResonanceMode(e.target.value)}>{loadout?.resonator?.combat?.modes.map((item) => <option key={item}>{item}</option>)}</select></label><label>Available action<select value={selectedActionId} onChange={(e) => setActionId(e.target.value)}>{loadout?.actions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{actionResult && <div className="action-meta"><span>{actionResult.action.damageType ?? "No damage type"}</span><span>{actionResult.action.talent} Lv{actionResult.action.level}</span><span>{actionResult.action.multipliers.reduce((sum, group) => sum + group.percent * group.hits, 0).toFixed(2)}% MV</span><span>{actionResult.action.multipliers.reduce((sum, group) => sum + group.hits, 0)} hits</span></div>}</Panel>
          <Panel title="Damage">{actionResult?.damage.status === "supported" ? <><Status partial={actionResult.partial}/><div className="damage-cards"><Metric label="Non Crit" value={actionResult.damage.total.nonCrit}/><Metric label="Crit" value={actionResult.damage.total.crit}/><Metric label="Expected" value={actionResult.damage.total.expected}/></div>{isStandardDamage(actionResult.damage) && <><table><thead><tr><th>Group</th><th>MV/hit</th><th>Hits</th><th>Non Crit</th><th>Crit</th><th>Expected</th></tr></thead><tbody>{actionResult.damage.hitGroups.map((group) => <tr key={group.groupIndex}><td>{group.groupIndex + 1}</td><td>{group.motionValuePercentPerHit}%</td><td>{group.hits}</td><td>{number(group.subtotal.nonCrit)}</td><td>{number(group.subtotal.crit)}</td><td>{number(group.subtotal.expected)}</td></tr>)}</tbody></table><Formula result={actionResult.damage}/></>}</> : <div className="unsupported"><strong>Formula not supported</strong><p>{actionResult?.damage.message ?? "Select an action."}</p></div>}</Panel>
          {!!actionResult?.outcomes.length && <Panel title="Personal sustain outcomes"><p className="hint">Nearby-team propagation is deferred; these are formula amounts only.</p><div className="damage-cards">{actionResult.outcomes.map((outcome,index)=><Metric key={`${outcome.kind}-${index}`} label={outcome.kind === "shield" ? `Shield · ${outcome.durationSeconds}s` : "Healing"} value={outcome.amount}/>)}</div></Panel>}
          <Panel title="Manual debug override"><p className="hint">Action Lab only. This is not the canonical rotation state.</p>{loadout?.effects.map((effect) => { const included = effect.rules.every((rule) => rule.accounting !== "runtime"); return <label className="effect-row" key={effect.id}><input type="checkbox" disabled={included} checked={!included && manual.includes(effect.id)} onChange={(e) => setManual(e.target.checked ? [...manual, effect.id] : manual.filter((id) => id !== effect.id))}/><span>{effect.label}</span>{included && <small>Included in final stats</small>}</label>; })}</Panel>
          <Panel title="Observed in-game damage"><label>Observed hit / total<input type="number" value={observed} onChange={(e) => setObserved(e.target.value)} placeholder="Enter observed value"/></label>{delta && <div className="comparison"><span>Calculated: {number(delta.calculated)}</span><span>Observed: {number(delta.observed)}</span><span>Delta: {number(delta.absoluteDelta)}</span><span>Error: {delta.percentageDelta === null ? "N/A" : `${delta.percentageDelta.toFixed(3)}%`}</span></div>}<button onClick={copySnapshot}>Copy validation snapshot</button></Panel>
        </> : <RotationView result={rotation}/>}
      </section>
      <aside className="lab-column"><Diagnostics diagnostics={[...(loadout?.diagnostics ?? []), ...(mode === "action" ? actionResult?.diagnostics ?? [] : rotation?.diagnostics ?? [])]}/>{rotation && mode === "rotation" && <><Timeline title="Event timeline" rows={rotation.eventLog.map((event) => ({ time: event.timestamp, kind: event.kind, detail: event.actionId ?? event.sourceId ?? "—", raw: event }))}/><Timeline title="Effects / state timeline" rows={rotation.stateTransitions.map((event) => ({ time: event.timestamp, kind: event.kind, detail: event.detail, raw: event }))}/></>}</aside>
    </div>
  </main>;
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="lab-panel"><h2>{title}</h2>{children}</section>; }
function Metric({ label, value }: { label: string; value: number }) { return <div><small>{label}</small><strong>{number(value)}</strong></div>; }
function Status({ partial }: { partial: boolean }) { return <span className={`status ${partial ? "partial" : "complete"}`}>{partial ? "PARTIAL" : "COMPLETE"}</span>; }
function Formula({ result }: { result: StandardDamageResult }) { const rows = [["Scaling stat", result.scalingAttribute], ["Effective scaling", number(result.scalingAttributeValue)], ["Motion Value", `${result.totalMotionValue * 100}%`], ["Element bonus", `${result.elementalDamageBonusPercent}%`], ["Damage type bonus", `${result.damageTypeBonusPercent}%`], ["All DMG bonus", `${result.allDamageBonusPercent}%`], ["Amplification", `${result.damageAmplificationPercent}%`], ["DEF reduction / ignore", `${result.defenseReduction} / ${result.defenseIgnore}`], ["DEF multiplier", result.defenseMultiplier.toFixed(6)], ["Base / effective RES", `${result.baseElementalResistance} / ${result.effectiveResistance}`], ["RES reduction / ignore", `${result.resistanceReduction} / ${result.resistanceIgnore}`], ["RES multiplier", result.resistanceMultiplier.toFixed(6)], ["Crit Rate", `${(result.effectiveCritRate * 100).toFixed(2)}%`], ["Crit DMG", `${result.critDamagePercent}%`], ["Expected Crit multiplier", result.expectedCritMultiplier.toFixed(6)]]; return <details className="formula"><summary>Why this damage?</summary><dl>{rows.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details>; }

function RotationView({ result }: { result?: PersonalCombatResult }) { if (!result) return <Panel title="Rotation Lab"><div className="unsupported">Simulation unavailable for this loadout.</div></Panel>; const duration = result.rotationDurationSeconds; return <><Panel title="Aemeath reference rotation"><div className="action-meta"><span>aemeath-s0-standard-no-quickswap</span><span>{duration.toFixed(2)}s</span><span>estimated-calibrated</span><span>community calibration</span></div></Panel><Panel title="Personal DPS result"><Status partial={result.partial}/><div className="damage-cards"><Metric label="Total expected" value={result.personalDamage.expected}/><Metric label="Personal DPS" value={result.personalDps.expected}/><Metric label="Non Crit" value={result.personalDamage.nonCrit}/><Metric label="Crit" value={result.personalDamage.crit}/></div>{result.partial && <p className="warning">Partial: unsupported or missing-context mechanics are excluded, never represented as zero damage.</p>}</Panel><Panel title="Breakdown"><table><thead><tr><th>Category</th><th>Non Crit</th><th>Crit</th><th>Expected</th></tr></thead><tbody>{Object.entries(result.breakdown).map(([name, amounts]) => <tr key={name}><td>{name}</td><td>{number(amounts.nonCrit)}</td><td>{number(amounts.crit)}</td><td>{number(amounts.expected)}</td></tr>)}</tbody></table><h3>By action</h3><table><thead><tr><th>Action</th><th>Damage</th><th>% total</th><th>DPS</th></tr></thead><tbody>{Object.entries(result.perAction).map(([name, amounts]) => <tr key={name}><td>{name}</td><td>{number(amounts.expected)}</td><td>{result.personalDamage.expected ? number(amounts.expected / result.personalDamage.expected * 100) : "—"}%</td><td>{number(amounts.expected / duration)}</td></tr>)}</tbody></table></Panel><Panel title="Coverage"><div className="coverage"><span>Relevant supported <b>{result.coverage.relevantSupported}</b></span><span>Relevant unsupported <b>{result.coverage.relevantUnsupported}</b></span><span>Modeled unused <b>{result.coverage.modeledUnused}</b></span><span>Missing context <b>{result.coverage.notEmittedDueToMissingContext}</b></span></div><p className="hint">Coverage describes emitted/model-visible mechanics, not the exhaustive kit.</p></Panel></>; }

function Diagnostics({ diagnostics }: { diagnostics: readonly { code: string; message: string }[] }) { const unique = [...new Map(diagnostics.map((item) => [`${item.code}:${item.message}`, item])).values()]; const groups = diagnosticsByFamily(unique); return <Panel title="Unsupported / diagnostics">{!unique.length ? <p className="hint">No diagnostics for the current result.</p> : Object.entries(groups).map(([family, items]) => <details key={family} open><summary>{family} ({items.length})</summary>{items.map((item, index) => <div className="diagnostic" key={`${item.code}-${index}`}><code>{item.code}</code><p>{item.message}</p></div>)}</details>)}</Panel>; }
function Timeline({ title, rows }: { title: string; rows: readonly { time: number; kind: string; detail: string; raw: unknown }[] }) { return <Panel title={title}><div className="timeline">{rows.map((row, index) => <details key={index}><summary><time>{row.time.toFixed(3)}s</time><b>{row.kind}</b><span>{row.detail}</span></summary><pre>{JSON.stringify(row.raw, null, 2)}</pre></details>)}</div></Panel>; }
