import type { CombatEffect, Sonata, SonataPieceBonus } from "@/domain/models";
import type { EffectDefinition } from "@/domain/effect-models";
import { generatedLegacySonataCanonicalIds } from "@/generated/precise-character-box-echo-presets";
import { trailblazingStar } from "./aemeath-combat";
import { voidThunder } from "./calcharo-runtime";
import { threadOfSeveredFate } from "./chisa-combat";

const aliasSource = {
  kind: "verified-game-data" as const,
  source: "WUWA GameDatabase V1 · canonical legacy Sonata bridge",
  gameVersion: "3.5",
  verifiedAt: "2026-08-20",
  notes:
    "Canonical GameDatabase Sonata ids are generated by exact name match. Existing reviewed runtime effects are reused rather than duplicated; Havoc Eclipse 2-piece is structured here so mixed Chisa accounting stays runtime-owned.",
};

function requiredEffects(sonata: Sonata, ids: readonly string[]): readonly CombatEffect[] {
  return ids.map((id) => {
    const matches = (sonata.effects ?? []).filter((effect) => effect.id === id);
    if (matches.length !== 1) {
      throw new Error(`${sonata.name} requires exactly one runtime effect ${id}, got ${matches.length}.`);
    }
    return matches[0]!;
  });
}

function canonicalSonata(
  legacy: Sonata,
  canonicalId: string,
  pieceBonuses: readonly SonataPieceBonus[],
): Sonata {
  return {
    ...legacy,
    id: canonicalId,
    pieceBonuses,
    source: {
      ...legacy.source,
      notes: `${legacy.source.notes ?? ""} Canonical GameDatabase id bridged for Echo-derived Sonata resolution.`.trim(),
    },
  };
}

const havocEclipseDefinition: EffectDefinition = {
  id: `${generatedLegacySonataCanonicalIds.havocEclipse}:2pc:havoc`,
  label: "Havoc Eclipse 2-piece — Havoc DMG",
  source: {
    id: generatedLegacySonataCanonicalIds.havocEclipse,
    type: "sonata",
    label: "Havoc Eclipse",
    metadata: aliasSource,
  },
  target: "self",
  activationPolicy: "initially-active",
  rules: [
    {
      id: "havoc-eclipse-2pc-havoc",
      label: "+10% Havoc DMG",
      accounting: "runtime",
      selectors: [{ kind: "element", anyOf: ["havoc"] }],
      modifiers: [
        { kind: "elemental-damage-bonus", stacking: "additive", value: 10 },
      ],
    },
  ],
};

const havocEclipseEffect: CombatEffect = {
  id: havocEclipseDefinition.id,
  name: havocEclipseDefinition.label,
  sourceId: generatedLegacySonataCanonicalIds.havocEclipse,
  trigger: "2 pieces equipped",
  target: "self",
  effect: "+10% Havoc DMG.",
  structuredEffect: havocEclipseDefinition,
  source: aliasSource,
};

const canonicalTrailblazingStar = canonicalSonata(
  trailblazingStar,
  generatedLegacySonataCanonicalIds.trailblazingStar,
  [
    { pieces: 2, effects: requiredEffects(trailblazingStar, ["trailblazing-2pc"]) },
    { pieces: 5, effects: requiredEffects(trailblazingStar, ["trailblazing-5pc"]) },
  ],
);

const canonicalVoidThunder = canonicalSonata(
  voidThunder,
  generatedLegacySonataCanonicalIds.voidThunder,
  [
    { pieces: 2, effects: requiredEffects(voidThunder, ["void-thunder-2pc"]) },
    { pieces: 5, effects: requiredEffects(voidThunder, ["void-thunder-5pc"]) },
  ],
);

const canonicalThreadOfSeveredFate = canonicalSonata(
  threadOfSeveredFate,
  generatedLegacySonataCanonicalIds.threadOfSeveredFate,
  [
    {
      pieces: 3,
      effects: requiredEffects(threadOfSeveredFate, ["thread-severed-fate-runtime"]),
    },
  ],
);

const canonicalHavocEclipse: Sonata = {
  id: generatedLegacySonataCanonicalIds.havocEclipse,
  name: "Havoc Eclipse",
  effectDescription: "2-piece: +10% Havoc DMG.",
  pieceBonuses: [{ pieces: 2, effects: [havocEclipseEffect] }],
  source: {
    ...aliasSource,
    notes: `${aliasSource.notes} Chisa's previous panel-baked +10% Havoc is intentionally moved here to preserve single-source accounting.`,
  },
};

export const canonicalLegacySonatas: readonly Sonata[] = [
  canonicalTrailblazingStar,
  canonicalVoidThunder,
  canonicalThreadOfSeveredFate,
  canonicalHavocEclipse,
];
